/*
ANSSL OpenAPI

ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package anssl

import (
	"encoding/json/v2"
	"fmt"
)

// checks if the CertificateListData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificateListData{}

// CertificateListData struct for CertificateListData
type CertificateListData struct {
	// 当前页证书列表。
	Certs []CertificateSummary `json:"certs"`
	// 总记录数。
	Total int64 `json:"total"`
	// 当前页码。
	Page int32 `json:"page"`
	// 当前页大小。
	Size int32 `json:"size"`
}

type _CertificateListData CertificateListData

// NewCertificateListData instantiates a new CertificateListData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificateListData(certs []CertificateSummary, total int64, page int32, size int32) *CertificateListData {
	this := CertificateListData{}
	this.Certs = certs
	this.Total = total
	this.Page = page
	this.Size = size
	return &this
}

// NewCertificateListDataWithDefaults instantiates a new CertificateListData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificateListDataWithDefaults() *CertificateListData {
	this := CertificateListData{}
	return &this
}

// GetCerts returns the Certs field value
func (o *CertificateListData) GetCerts() []CertificateSummary {
	if o == nil {
		var ret []CertificateSummary
		return ret
	}

	return o.Certs
}

// GetCertsOk returns a tuple with the Certs field value
// and a boolean to check if the value has been set.
func (o *CertificateListData) GetCertsOk() ([]CertificateSummary, bool) {
	if o == nil {
		return nil, false
	}
	return o.Certs, true
}

// SetCerts sets field value
func (o *CertificateListData) SetCerts(v []CertificateSummary) {
	o.Certs = v
}

// GetTotal returns the Total field value
func (o *CertificateListData) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *CertificateListData) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *CertificateListData) SetTotal(v int64) {
	o.Total = v
}

// GetPage returns the Page field value
func (o *CertificateListData) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *CertificateListData) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *CertificateListData) SetPage(v int32) {
	o.Page = v
}

// GetSize returns the Size field value
func (o *CertificateListData) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *CertificateListData) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *CertificateListData) SetSize(v int32) {
	o.Size = v
}

func (o CertificateListData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificateListData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["certs"] = o.Certs
	toSerialize["total"] = o.Total
	toSerialize["page"] = o.Page
	toSerialize["size"] = o.Size
	return toSerialize, nil
}

func (o *CertificateListData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"certs",
		"total",
		"page",
		"size",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCertificateListData := _CertificateListData{}

	err = json.Unmarshal(data, &varCertificateListData, json.RejectUnknownMembers(true))

	if err != nil {
		return err
	}

	*o = CertificateListData(varCertificateListData)

	return err
}

type NullableCertificateListData struct {
	value *CertificateListData
	isSet bool
}

func (v NullableCertificateListData) Get() *CertificateListData {
	return v.value
}

func (v *NullableCertificateListData) Set(val *CertificateListData) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateListData) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateListData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateListData(val *CertificateListData) *NullableCertificateListData {
	return &NullableCertificateListData{value: val, isSet: true}
}

func (v NullableCertificateListData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateListData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
