/*
ANSSL OpenAPI

ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package anssl

import (
	"encoding/json/v2"
	"fmt"
)

// CertificateOperationStatus 异步操作执行状态。
type CertificateOperationStatus string

// List of CertificateOperationStatus
const (
	CERTIFICATEOPERATIONSTATUS_PENDING            CertificateOperationStatus = "pending"
	CERTIFICATEOPERATIONSTATUS_RUNNING            CertificateOperationStatus = "running"
	CERTIFICATEOPERATIONSTATUS_WAITING_VALIDATION CertificateOperationStatus = "waiting_validation"
	CERTIFICATEOPERATIONSTATUS_SUCCEEDED          CertificateOperationStatus = "succeeded"
	CERTIFICATEOPERATIONSTATUS_FAILED             CertificateOperationStatus = "failed"
	CERTIFICATEOPERATIONSTATUS_CANCELED           CertificateOperationStatus = "canceled"
	CERTIFICATEOPERATIONSTATUS_UNKNOWN            CertificateOperationStatus = "unknown"
)

// All allowed values of CertificateOperationStatus enum
var AllowedCertificateOperationStatusEnumValues = []CertificateOperationStatus{
	"pending",
	"running",
	"waiting_validation",
	"succeeded",
	"failed",
	"canceled",
	"unknown",
}

func (v *CertificateOperationStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CertificateOperationStatus(value)
	for _, existing := range AllowedCertificateOperationStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CertificateOperationStatus", value)
}

// NewCertificateOperationStatusFromValue returns a pointer to a valid CertificateOperationStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCertificateOperationStatusFromValue(v string) (*CertificateOperationStatus, error) {
	ev := CertificateOperationStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CertificateOperationStatus: valid values are %v", v, AllowedCertificateOperationStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CertificateOperationStatus) IsValid() bool {
	for _, existing := range AllowedCertificateOperationStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CertificateOperationStatus value
func (v CertificateOperationStatus) Ptr() *CertificateOperationStatus {
	return &v
}

type NullableCertificateOperationStatus struct {
	value *CertificateOperationStatus
	isSet bool
}

func (v NullableCertificateOperationStatus) Get() *CertificateOperationStatus {
	return v.value
}

func (v *NullableCertificateOperationStatus) Set(val *CertificateOperationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateOperationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateOperationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateOperationStatus(val *CertificateOperationStatus) *NullableCertificateOperationStatus {
	return &NullableCertificateOperationStatus{value: val, isSet: true}
}

func (v NullableCertificateOperationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateOperationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
