/*
ANSSL OpenAPI

ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package anssl

import (
	"encoding/json/v2"
	"fmt"
)

// checks if the CheckDomainRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckDomainRequest{}

// CheckDomainRequest struct for CheckDomainRequest
type CheckDomainRequest struct {
	// 可选关联证书标识。
	CertKey *string `json:"certKey,omitempty"`
	// 非空且不重复的域名列表，最多 100 项。
	Domains []string `json:"domains"`
}

type _CheckDomainRequest CheckDomainRequest

// NewCheckDomainRequest instantiates a new CheckDomainRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckDomainRequest(domains []string) *CheckDomainRequest {
	this := CheckDomainRequest{}
	this.Domains = domains
	return &this
}

// NewCheckDomainRequestWithDefaults instantiates a new CheckDomainRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckDomainRequestWithDefaults() *CheckDomainRequest {
	this := CheckDomainRequest{}
	return &this
}

// GetCertKey returns the CertKey field value if set, zero value otherwise.
func (o *CheckDomainRequest) GetCertKey() string {
	if o == nil || IsNil(o.CertKey) {
		var ret string
		return ret
	}
	return *o.CertKey
}

// GetCertKeyOk returns a tuple with the CertKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckDomainRequest) GetCertKeyOk() (*string, bool) {
	if o == nil || IsNil(o.CertKey) {
		return nil, false
	}
	return o.CertKey, true
}

// HasCertKey returns a boolean if a field has been set.
func (o *CheckDomainRequest) HasCertKey() bool {
	if o != nil && !IsNil(o.CertKey) {
		return true
	}

	return false
}

// SetCertKey gets a reference to the given string and assigns it to the CertKey field.
func (o *CheckDomainRequest) SetCertKey(v string) {
	o.CertKey = &v
}

// GetDomains returns the Domains field value
func (o *CheckDomainRequest) GetDomains() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value
// and a boolean to check if the value has been set.
func (o *CheckDomainRequest) GetDomainsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Domains, true
}

// SetDomains sets field value
func (o *CheckDomainRequest) SetDomains(v []string) {
	o.Domains = v
}

func (o CheckDomainRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckDomainRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CertKey) {
		toSerialize["certKey"] = o.CertKey
	}
	toSerialize["domains"] = o.Domains
	return toSerialize, nil
}

func (o *CheckDomainRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"domains",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckDomainRequest := _CheckDomainRequest{}

	err = json.Unmarshal(data, &varCheckDomainRequest, json.RejectUnknownMembers(true))

	if err != nil {
		return err
	}

	*o = CheckDomainRequest(varCheckDomainRequest)

	return err
}

type NullableCheckDomainRequest struct {
	value *CheckDomainRequest
	isSet bool
}

func (v NullableCheckDomainRequest) Get() *CheckDomainRequest {
	return v.value
}

func (v *NullableCheckDomainRequest) Set(val *CheckDomainRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckDomainRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckDomainRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckDomainRequest(val *CheckDomainRequest) *NullableCheckDomainRequest {
	return &NullableCheckDomainRequest{value: val, isSet: true}
}

func (v NullableCheckDomainRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckDomainRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
