/*
ANSSL OpenAPI

ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package anssl

import (
	"encoding/json/v2"
	"fmt"
)

// VerificationType ACME 验证方式。
type VerificationType string

// List of VerificationType
const (
	VERIFICATIONTYPE_DNS  VerificationType = "dns"
	VERIFICATIONTYPE_HTTP VerificationType = "http"
)

// All allowed values of VerificationType enum
var AllowedVerificationTypeEnumValues = []VerificationType{
	"dns",
	"http",
}

func (v *VerificationType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := VerificationType(value)
	for _, existing := range AllowedVerificationTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid VerificationType", value)
}

// NewVerificationTypeFromValue returns a pointer to a valid VerificationType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewVerificationTypeFromValue(v string) (*VerificationType, error) {
	ev := VerificationType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for VerificationType: valid values are %v", v, AllowedVerificationTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v VerificationType) IsValid() bool {
	for _, existing := range AllowedVerificationTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to VerificationType value
func (v VerificationType) Ptr() *VerificationType {
	return &v
}

type NullableVerificationType struct {
	value *VerificationType
	isSet bool
}

func (v NullableVerificationType) Get() *VerificationType {
	return v.value
}

func (v *NullableVerificationType) Set(val *VerificationType) {
	v.value = val
	v.isSet = true
}

func (v NullableVerificationType) IsSet() bool {
	return v.isSet
}

func (v *NullableVerificationType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerificationType(val *VerificationType) *NullableVerificationType {
	return &NullableVerificationType{value: val, isSet: true}
}

func (v NullableVerificationType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerificationType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
