/*
ANSSL OpenAPI

ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package anssl

import (
	"encoding/json/v2"
	"fmt"
)

// checks if the DeleteCertificateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteCertificateRequest{}

// DeleteCertificateRequest struct for DeleteCertificateRequest
type DeleteCertificateRequest struct {
	// 固定为 delete。
	Action string `json:"action"`
	// 要删除的平台证书标识。
	CertKey string `json:"certKey"`
}

type _DeleteCertificateRequest DeleteCertificateRequest

// NewDeleteCertificateRequest instantiates a new DeleteCertificateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteCertificateRequest(action string, certKey string) *DeleteCertificateRequest {
	this := DeleteCertificateRequest{}
	this.Action = action
	this.CertKey = certKey
	return &this
}

// NewDeleteCertificateRequestWithDefaults instantiates a new DeleteCertificateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteCertificateRequestWithDefaults() *DeleteCertificateRequest {
	this := DeleteCertificateRequest{}
	return &this
}

// GetAction returns the Action field value
func (o *DeleteCertificateRequest) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *DeleteCertificateRequest) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *DeleteCertificateRequest) SetAction(v string) {
	o.Action = v
}

// GetCertKey returns the CertKey field value
func (o *DeleteCertificateRequest) GetCertKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CertKey
}

// GetCertKeyOk returns a tuple with the CertKey field value
// and a boolean to check if the value has been set.
func (o *DeleteCertificateRequest) GetCertKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CertKey, true
}

// SetCertKey sets field value
func (o *DeleteCertificateRequest) SetCertKey(v string) {
	o.CertKey = v
}

func (o DeleteCertificateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteCertificateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	toSerialize["certKey"] = o.CertKey
	return toSerialize, nil
}

func (o *DeleteCertificateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"certKey",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteCertificateRequest := _DeleteCertificateRequest{}

	err = json.Unmarshal(data, &varDeleteCertificateRequest, json.RejectUnknownMembers(true))

	if err != nil {
		return err
	}

	*o = DeleteCertificateRequest(varDeleteCertificateRequest)

	return err
}

type NullableDeleteCertificateRequest struct {
	value *DeleteCertificateRequest
	isSet bool
}

func (v NullableDeleteCertificateRequest) Get() *DeleteCertificateRequest {
	return v.value
}

func (v *NullableDeleteCertificateRequest) Set(val *DeleteCertificateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteCertificateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteCertificateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteCertificateRequest(val *DeleteCertificateRequest) *NullableDeleteCertificateRequest {
	return &NullableDeleteCertificateRequest{value: val, isSet: true}
}

func (v NullableDeleteCertificateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteCertificateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
