/*
ANSSL OpenAPI

ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package anssl

import (
	"encoding/json/v2"
	"fmt"
)

// checks if the CertificateOperationSuccessResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificateOperationSuccessResponse{}

// CertificateOperationSuccessResponse struct for CertificateOperationSuccessResponse
type CertificateOperationSuccessResponse struct {
	Code    SuccessCode          `json:"code"`
	Message SuccessMessage       `json:"message"`
	Data    CertificateOperation `json:"data"`
}

type _CertificateOperationSuccessResponse CertificateOperationSuccessResponse

// NewCertificateOperationSuccessResponse instantiates a new CertificateOperationSuccessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificateOperationSuccessResponse(code SuccessCode, message SuccessMessage, data CertificateOperation) *CertificateOperationSuccessResponse {
	this := CertificateOperationSuccessResponse{}
	this.Code = code
	this.Message = message
	this.Data = data
	return &this
}

// NewCertificateOperationSuccessResponseWithDefaults instantiates a new CertificateOperationSuccessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificateOperationSuccessResponseWithDefaults() *CertificateOperationSuccessResponse {
	this := CertificateOperationSuccessResponse{}
	return &this
}

// GetCode returns the Code field value
func (o *CertificateOperationSuccessResponse) GetCode() SuccessCode {
	if o == nil {
		var ret SuccessCode
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *CertificateOperationSuccessResponse) GetCodeOk() (*SuccessCode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *CertificateOperationSuccessResponse) SetCode(v SuccessCode) {
	o.Code = v
}

// GetMessage returns the Message field value
func (o *CertificateOperationSuccessResponse) GetMessage() SuccessMessage {
	if o == nil {
		var ret SuccessMessage
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *CertificateOperationSuccessResponse) GetMessageOk() (*SuccessMessage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *CertificateOperationSuccessResponse) SetMessage(v SuccessMessage) {
	o.Message = v
}

// GetData returns the Data field value
func (o *CertificateOperationSuccessResponse) GetData() CertificateOperation {
	if o == nil {
		var ret CertificateOperation
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CertificateOperationSuccessResponse) GetDataOk() (*CertificateOperation, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CertificateOperationSuccessResponse) SetData(v CertificateOperation) {
	o.Data = v
}

func (o CertificateOperationSuccessResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificateOperationSuccessResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["message"] = o.Message
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CertificateOperationSuccessResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"message",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCertificateOperationSuccessResponse := _CertificateOperationSuccessResponse{}

	err = json.Unmarshal(data, &varCertificateOperationSuccessResponse, json.RejectUnknownMembers(true))

	if err != nil {
		return err
	}

	*o = CertificateOperationSuccessResponse(varCertificateOperationSuccessResponse)

	return err
}

type NullableCertificateOperationSuccessResponse struct {
	value *CertificateOperationSuccessResponse
	isSet bool
}

func (v NullableCertificateOperationSuccessResponse) Get() *CertificateOperationSuccessResponse {
	return v.value
}

func (v *NullableCertificateOperationSuccessResponse) Set(val *CertificateOperationSuccessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateOperationSuccessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateOperationSuccessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateOperationSuccessResponse(val *CertificateOperationSuccessResponse) *NullableCertificateOperationSuccessResponse {
	return &NullableCertificateOperationSuccessResponse{value: val, isSet: true}
}

func (v NullableCertificateOperationSuccessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateOperationSuccessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
