/*
ANSSL OpenAPI

ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package anssl

import (
	"encoding/json/v2"
	"fmt"
	"time"
)

// checks if the CertificateOperation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificateOperation{}

// CertificateOperation struct for CertificateOperation
type CertificateOperation struct {
	// 避免跨语言 int64 精度问题的十进制字符串操作 ID。
	RequestedOperationId string `json:"requestedOperationId" validate:"regexp=^[1-9][0-9]*$"`
	// 避免跨语言 int64 精度问题的十进制字符串操作 ID。
	OperationId string `json:"operationId" validate:"regexp=^[1-9][0-9]*$"`
	// 关联证书外部标识。
	CertKey string                     `json:"certKey"`
	Type    CertificateOperationType   `json:"type"`
	Status  CertificateOperationStatus `json:"status"`
	// 实际使用的幂等键。
	RequestKey string `json:"requestKey"`
	// 已执行次数。
	Attempt int32 `json:"attempt"`
	// 最大执行次数。
	MaxAttempts int32 `json:"maxAttempts"`
	// 最近失败原因。
	FailureReason *string `json:"failureReason,omitempty"`
	// 操作创建时间。
	CreatedAt time.Time `json:"createdAt"`
	// 操作更新时间。
	UpdatedAt time.Time `json:"updatedAt"`
	// 首次开始时间。
	StartedAt *time.Time `json:"startedAt,omitempty"`
	// 进入终态时间。
	FinishedAt *time.Time `json:"finishedAt,omitempty"`
}

type _CertificateOperation CertificateOperation

// NewCertificateOperation instantiates a new CertificateOperation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificateOperation(requestedOperationId string, operationId string, certKey string, type_ CertificateOperationType, status CertificateOperationStatus, requestKey string, attempt int32, maxAttempts int32, createdAt time.Time, updatedAt time.Time) *CertificateOperation {
	this := CertificateOperation{}
	this.RequestedOperationId = requestedOperationId
	this.OperationId = operationId
	this.CertKey = certKey
	this.Type = type_
	this.Status = status
	this.RequestKey = requestKey
	this.Attempt = attempt
	this.MaxAttempts = maxAttempts
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewCertificateOperationWithDefaults instantiates a new CertificateOperation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificateOperationWithDefaults() *CertificateOperation {
	this := CertificateOperation{}
	return &this
}

// GetRequestedOperationId returns the RequestedOperationId field value
func (o *CertificateOperation) GetRequestedOperationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestedOperationId
}

// GetRequestedOperationIdOk returns a tuple with the RequestedOperationId field value
// and a boolean to check if the value has been set.
func (o *CertificateOperation) GetRequestedOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestedOperationId, true
}

// SetRequestedOperationId sets field value
func (o *CertificateOperation) SetRequestedOperationId(v string) {
	o.RequestedOperationId = v
}

// GetOperationId returns the OperationId field value
func (o *CertificateOperation) GetOperationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationId
}

// GetOperationIdOk returns a tuple with the OperationId field value
// and a boolean to check if the value has been set.
func (o *CertificateOperation) GetOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationId, true
}

// SetOperationId sets field value
func (o *CertificateOperation) SetOperationId(v string) {
	o.OperationId = v
}

// GetCertKey returns the CertKey field value
func (o *CertificateOperation) GetCertKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CertKey
}

// GetCertKeyOk returns a tuple with the CertKey field value
// and a boolean to check if the value has been set.
func (o *CertificateOperation) GetCertKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CertKey, true
}

// SetCertKey sets field value
func (o *CertificateOperation) SetCertKey(v string) {
	o.CertKey = v
}

// GetType returns the Type field value
func (o *CertificateOperation) GetType() CertificateOperationType {
	if o == nil {
		var ret CertificateOperationType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CertificateOperation) GetTypeOk() (*CertificateOperationType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CertificateOperation) SetType(v CertificateOperationType) {
	o.Type = v
}

// GetStatus returns the Status field value
func (o *CertificateOperation) GetStatus() CertificateOperationStatus {
	if o == nil {
		var ret CertificateOperationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CertificateOperation) GetStatusOk() (*CertificateOperationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CertificateOperation) SetStatus(v CertificateOperationStatus) {
	o.Status = v
}

// GetRequestKey returns the RequestKey field value
func (o *CertificateOperation) GetRequestKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestKey
}

// GetRequestKeyOk returns a tuple with the RequestKey field value
// and a boolean to check if the value has been set.
func (o *CertificateOperation) GetRequestKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestKey, true
}

// SetRequestKey sets field value
func (o *CertificateOperation) SetRequestKey(v string) {
	o.RequestKey = v
}

// GetAttempt returns the Attempt field value
func (o *CertificateOperation) GetAttempt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Attempt
}

// GetAttemptOk returns a tuple with the Attempt field value
// and a boolean to check if the value has been set.
func (o *CertificateOperation) GetAttemptOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attempt, true
}

// SetAttempt sets field value
func (o *CertificateOperation) SetAttempt(v int32) {
	o.Attempt = v
}

// GetMaxAttempts returns the MaxAttempts field value
func (o *CertificateOperation) GetMaxAttempts() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxAttempts
}

// GetMaxAttemptsOk returns a tuple with the MaxAttempts field value
// and a boolean to check if the value has been set.
func (o *CertificateOperation) GetMaxAttemptsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxAttempts, true
}

// SetMaxAttempts sets field value
func (o *CertificateOperation) SetMaxAttempts(v int32) {
	o.MaxAttempts = v
}

// GetFailureReason returns the FailureReason field value if set, zero value otherwise.
func (o *CertificateOperation) GetFailureReason() string {
	if o == nil || IsNil(o.FailureReason) {
		var ret string
		return ret
	}
	return *o.FailureReason
}

// GetFailureReasonOk returns a tuple with the FailureReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateOperation) GetFailureReasonOk() (*string, bool) {
	if o == nil || IsNil(o.FailureReason) {
		return nil, false
	}
	return o.FailureReason, true
}

// HasFailureReason returns a boolean if a field has been set.
func (o *CertificateOperation) HasFailureReason() bool {
	if o != nil && !IsNil(o.FailureReason) {
		return true
	}

	return false
}

// SetFailureReason gets a reference to the given string and assigns it to the FailureReason field.
func (o *CertificateOperation) SetFailureReason(v string) {
	o.FailureReason = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CertificateOperation) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CertificateOperation) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CertificateOperation) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *CertificateOperation) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *CertificateOperation) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *CertificateOperation) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *CertificateOperation) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateOperation) GetStartedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartedAt) {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *CertificateOperation) HasStartedAt() bool {
	if o != nil && !IsNil(o.StartedAt) {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given time.Time and assigns it to the StartedAt field.
func (o *CertificateOperation) SetStartedAt(v time.Time) {
	o.StartedAt = &v
}

// GetFinishedAt returns the FinishedAt field value if set, zero value otherwise.
func (o *CertificateOperation) GetFinishedAt() time.Time {
	if o == nil || IsNil(o.FinishedAt) {
		var ret time.Time
		return ret
	}
	return *o.FinishedAt
}

// GetFinishedAtOk returns a tuple with the FinishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateOperation) GetFinishedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.FinishedAt) {
		return nil, false
	}
	return o.FinishedAt, true
}

// HasFinishedAt returns a boolean if a field has been set.
func (o *CertificateOperation) HasFinishedAt() bool {
	if o != nil && !IsNil(o.FinishedAt) {
		return true
	}

	return false
}

// SetFinishedAt gets a reference to the given time.Time and assigns it to the FinishedAt field.
func (o *CertificateOperation) SetFinishedAt(v time.Time) {
	o.FinishedAt = &v
}

func (o CertificateOperation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificateOperation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requestedOperationId"] = o.RequestedOperationId
	toSerialize["operationId"] = o.OperationId
	toSerialize["certKey"] = o.CertKey
	toSerialize["type"] = o.Type
	toSerialize["status"] = o.Status
	toSerialize["requestKey"] = o.RequestKey
	toSerialize["attempt"] = o.Attempt
	toSerialize["maxAttempts"] = o.MaxAttempts
	if !IsNil(o.FailureReason) {
		toSerialize["failureReason"] = o.FailureReason
	}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	if !IsNil(o.StartedAt) {
		toSerialize["startedAt"] = o.StartedAt
	}
	if !IsNil(o.FinishedAt) {
		toSerialize["finishedAt"] = o.FinishedAt
	}
	return toSerialize, nil
}

func (o *CertificateOperation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requestedOperationId",
		"operationId",
		"certKey",
		"type",
		"status",
		"requestKey",
		"attempt",
		"maxAttempts",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCertificateOperation := _CertificateOperation{}

	err = json.Unmarshal(data, &varCertificateOperation, json.RejectUnknownMembers(true))

	if err != nil {
		return err
	}

	*o = CertificateOperation(varCertificateOperation)

	return err
}

type NullableCertificateOperation struct {
	value *CertificateOperation
	isSet bool
}

func (v NullableCertificateOperation) Get() *CertificateOperation {
	return v.value
}

func (v *NullableCertificateOperation) Set(val *CertificateOperation) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateOperation) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateOperation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateOperation(val *CertificateOperation) *NullableCertificateOperation {
	return &NullableCertificateOperation{value: val, isSet: true}
}

func (v NullableCertificateOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateOperation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
