/*
ANSSL OpenAPI

ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package anssl

import (
	"encoding/json/v2"
	"fmt"
)

// checks if the Error409 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Error409{}

// Error409 struct for Error409
type Error409 struct {
	// 与 HTTP 409 一致的错误码。
	Code int32 `json:"code"`
	// 不应被客户端用于分支判断的可读错误信息。
	Message string `json:"message"`
}

type _Error409 Error409

// NewError409 instantiates a new Error409 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewError409(code int32, message string) *Error409 {
	this := Error409{}
	this.Code = code
	this.Message = message
	return &this
}

// NewError409WithDefaults instantiates a new Error409 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewError409WithDefaults() *Error409 {
	this := Error409{}
	return &this
}

// GetCode returns the Code field value
func (o *Error409) GetCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *Error409) GetCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *Error409) SetCode(v int32) {
	o.Code = v
}

// GetMessage returns the Message field value
func (o *Error409) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *Error409) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *Error409) SetMessage(v string) {
	o.Message = v
}

func (o Error409) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Error409) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *Error409) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varError409 := _Error409{}

	err = json.Unmarshal(data, &varError409, json.RejectUnknownMembers(true))

	if err != nil {
		return err
	}

	*o = Error409(varError409)

	return err
}

type NullableError409 struct {
	value *Error409
	isSet bool
}

func (v NullableError409) Get() *Error409 {
	return v.value
}

func (v *NullableError409) Set(val *Error409) {
	v.value = val
	v.isSet = true
}

func (v NullableError409) IsSet() bool {
	return v.isSet
}

func (v *NullableError409) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableError409(val *Error409) *NullableError409 {
	return &NullableError409{value: val, isSet: true}
}

func (v NullableError409) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableError409) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
