/*
ANSSL OpenAPI

ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package anssl

import (
	"encoding/json/v2"
	"fmt"
)

// checks if the CertificateListSuccessResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificateListSuccessResponse{}

// CertificateListSuccessResponse struct for CertificateListSuccessResponse
type CertificateListSuccessResponse struct {
	Code    SuccessCode         `json:"code"`
	Message SuccessMessage      `json:"message"`
	Data    CertificateListData `json:"data"`
}

type _CertificateListSuccessResponse CertificateListSuccessResponse

// NewCertificateListSuccessResponse instantiates a new CertificateListSuccessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificateListSuccessResponse(code SuccessCode, message SuccessMessage, data CertificateListData) *CertificateListSuccessResponse {
	this := CertificateListSuccessResponse{}
	this.Code = code
	this.Message = message
	this.Data = data
	return &this
}

// NewCertificateListSuccessResponseWithDefaults instantiates a new CertificateListSuccessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificateListSuccessResponseWithDefaults() *CertificateListSuccessResponse {
	this := CertificateListSuccessResponse{}
	return &this
}

// GetCode returns the Code field value
func (o *CertificateListSuccessResponse) GetCode() SuccessCode {
	if o == nil {
		var ret SuccessCode
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *CertificateListSuccessResponse) GetCodeOk() (*SuccessCode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *CertificateListSuccessResponse) SetCode(v SuccessCode) {
	o.Code = v
}

// GetMessage returns the Message field value
func (o *CertificateListSuccessResponse) GetMessage() SuccessMessage {
	if o == nil {
		var ret SuccessMessage
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *CertificateListSuccessResponse) GetMessageOk() (*SuccessMessage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *CertificateListSuccessResponse) SetMessage(v SuccessMessage) {
	o.Message = v
}

// GetData returns the Data field value
func (o *CertificateListSuccessResponse) GetData() CertificateListData {
	if o == nil {
		var ret CertificateListData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CertificateListSuccessResponse) GetDataOk() (*CertificateListData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CertificateListSuccessResponse) SetData(v CertificateListData) {
	o.Data = v
}

func (o CertificateListSuccessResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificateListSuccessResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["message"] = o.Message
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CertificateListSuccessResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"message",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCertificateListSuccessResponse := _CertificateListSuccessResponse{}

	err = json.Unmarshal(data, &varCertificateListSuccessResponse, json.RejectUnknownMembers(true))

	if err != nil {
		return err
	}

	*o = CertificateListSuccessResponse(varCertificateListSuccessResponse)

	return err
}

type NullableCertificateListSuccessResponse struct {
	value *CertificateListSuccessResponse
	isSet bool
}

func (v NullableCertificateListSuccessResponse) Get() *CertificateListSuccessResponse {
	return v.value
}

func (v *NullableCertificateListSuccessResponse) Set(val *CertificateListSuccessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateListSuccessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateListSuccessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateListSuccessResponse(val *CertificateListSuccessResponse) *NullableCertificateListSuccessResponse {
	return &NullableCertificateListSuccessResponse{value: val, isSet: true}
}

func (v NullableCertificateListSuccessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateListSuccessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
