/*
ANSSL OpenAPI

ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package anssl

import (
	"encoding/json/v2"
	"fmt"
)

// SuccessCode 成功 envelope code。
type SuccessCode int32

// List of SuccessCode
const (
	SUCCESSCODE__0 SuccessCode = 0
)

// All allowed values of SuccessCode enum
var AllowedSuccessCodeEnumValues = []SuccessCode{
	0,
}

func (v *SuccessCode) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SuccessCode(value)
	for _, existing := range AllowedSuccessCodeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SuccessCode", value)
}

// NewSuccessCodeFromValue returns a pointer to a valid SuccessCode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSuccessCodeFromValue(v int32) (*SuccessCode, error) {
	ev := SuccessCode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SuccessCode: valid values are %v", v, AllowedSuccessCodeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SuccessCode) IsValid() bool {
	for _, existing := range AllowedSuccessCodeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SuccessCode value
func (v SuccessCode) Ptr() *SuccessCode {
	return &v
}

type NullableSuccessCode struct {
	value *SuccessCode
	isSet bool
}

func (v NullableSuccessCode) Get() *SuccessCode {
	return v.value
}

func (v *NullableSuccessCode) Set(val *SuccessCode) {
	v.value = val
	v.isSet = true
}

func (v NullableSuccessCode) IsSet() bool {
	return v.isSet
}

func (v *NullableSuccessCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuccessCode(val *SuccessCode) *NullableSuccessCode {
	return &NullableSuccessCode{value: val, isSet: true}
}

func (v NullableSuccessCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuccessCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
