/*
ANSSL OpenAPI

ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package anssl

import (
	"encoding/json/v2"
	"fmt"
)

// SuccessMessage 成功 envelope message。
type SuccessMessage string

// List of SuccessMessage
const (
	SUCCESSMESSAGE_SUCCESS SuccessMessage = "success"
)

// All allowed values of SuccessMessage enum
var AllowedSuccessMessageEnumValues = []SuccessMessage{
	"success",
}

func (v *SuccessMessage) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SuccessMessage(value)
	for _, existing := range AllowedSuccessMessageEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SuccessMessage", value)
}

// NewSuccessMessageFromValue returns a pointer to a valid SuccessMessage
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSuccessMessageFromValue(v string) (*SuccessMessage, error) {
	ev := SuccessMessage(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SuccessMessage: valid values are %v", v, AllowedSuccessMessageEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SuccessMessage) IsValid() bool {
	for _, existing := range AllowedSuccessMessageEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SuccessMessage value
func (v SuccessMessage) Ptr() *SuccessMessage {
	return &v
}

type NullableSuccessMessage struct {
	value *SuccessMessage
	isSet bool
}

func (v NullableSuccessMessage) Get() *SuccessMessage {
	return v.value
}

func (v *NullableSuccessMessage) Set(val *SuccessMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableSuccessMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableSuccessMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuccessMessage(val *SuccessMessage) *NullableSuccessMessage {
	return &NullableSuccessMessage{value: val, isSet: true}
}

func (v NullableSuccessMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuccessMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
