/*
ANSSL OpenAPI

ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package anssl

import (
	"encoding/json/v2"
	"fmt"
)

// CertificateOperationType 异步证书操作类型。
type CertificateOperationType string

// List of CertificateOperationType
const (
	CERTIFICATEOPERATIONTYPE_APPLY   CertificateOperationType = "apply"
	CERTIFICATEOPERATIONTYPE_RENEW   CertificateOperationType = "renew"
	CERTIFICATEOPERATIONTYPE_REVOKE  CertificateOperationType = "revoke"
	CERTIFICATEOPERATIONTYPE_UNKNOWN CertificateOperationType = "unknown"
)

// All allowed values of CertificateOperationType enum
var AllowedCertificateOperationTypeEnumValues = []CertificateOperationType{
	"apply",
	"renew",
	"revoke",
	"unknown",
}

func (v *CertificateOperationType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CertificateOperationType(value)
	for _, existing := range AllowedCertificateOperationTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CertificateOperationType", value)
}

// NewCertificateOperationTypeFromValue returns a pointer to a valid CertificateOperationType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCertificateOperationTypeFromValue(v string) (*CertificateOperationType, error) {
	ev := CertificateOperationType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CertificateOperationType: valid values are %v", v, AllowedCertificateOperationTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CertificateOperationType) IsValid() bool {
	for _, existing := range AllowedCertificateOperationTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CertificateOperationType value
func (v CertificateOperationType) Ptr() *CertificateOperationType {
	return &v
}

type NullableCertificateOperationType struct {
	value *CertificateOperationType
	isSet bool
}

func (v NullableCertificateOperationType) Get() *CertificateOperationType {
	return v.value
}

func (v *NullableCertificateOperationType) Set(val *CertificateOperationType) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateOperationType) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateOperationType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateOperationType(val *CertificateOperationType) *NullableCertificateOperationType {
	return &NullableCertificateOperationType{value: val, isSet: true}
}

func (v NullableCertificateOperationType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateOperationType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
