/*
ANSSL OpenAPI

ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package anssl

import (
	"encoding/json/v2"
	"fmt"
)

// checks if the CheckDomainItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckDomainItem{}

// CheckDomainItem struct for CheckDomainItem
type CheckDomainItem struct {
	// 被检查的域名。
	Domain string `json:"domain"`
	// CNAME 记录名。
	Key string `json:"key"`
	// 原始 challenge 记录名。
	OriginKey string `json:"originKey"`
	// CNAME 目标值。
	Value string `json:"value"`
	// 可读解析状态。
	Status string `json:"status"`
	// 0 未知、1 正常、2 失败。
	StatusCode int32 `json:"statusCode"`
}

type _CheckDomainItem CheckDomainItem

// NewCheckDomainItem instantiates a new CheckDomainItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckDomainItem(domain string, key string, originKey string, value string, status string, statusCode int32) *CheckDomainItem {
	this := CheckDomainItem{}
	this.Domain = domain
	this.Key = key
	this.OriginKey = originKey
	this.Value = value
	this.Status = status
	this.StatusCode = statusCode
	return &this
}

// NewCheckDomainItemWithDefaults instantiates a new CheckDomainItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckDomainItemWithDefaults() *CheckDomainItem {
	this := CheckDomainItem{}
	return &this
}

// GetDomain returns the Domain field value
func (o *CheckDomainItem) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *CheckDomainItem) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *CheckDomainItem) SetDomain(v string) {
	o.Domain = v
}

// GetKey returns the Key field value
func (o *CheckDomainItem) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *CheckDomainItem) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *CheckDomainItem) SetKey(v string) {
	o.Key = v
}

// GetOriginKey returns the OriginKey field value
func (o *CheckDomainItem) GetOriginKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OriginKey
}

// GetOriginKeyOk returns a tuple with the OriginKey field value
// and a boolean to check if the value has been set.
func (o *CheckDomainItem) GetOriginKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OriginKey, true
}

// SetOriginKey sets field value
func (o *CheckDomainItem) SetOriginKey(v string) {
	o.OriginKey = v
}

// GetValue returns the Value field value
func (o *CheckDomainItem) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *CheckDomainItem) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *CheckDomainItem) SetValue(v string) {
	o.Value = v
}

// GetStatus returns the Status field value
func (o *CheckDomainItem) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CheckDomainItem) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CheckDomainItem) SetStatus(v string) {
	o.Status = v
}

// GetStatusCode returns the StatusCode field value
func (o *CheckDomainItem) GetStatusCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value
// and a boolean to check if the value has been set.
func (o *CheckDomainItem) GetStatusCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusCode, true
}

// SetStatusCode sets field value
func (o *CheckDomainItem) SetStatusCode(v int32) {
	o.StatusCode = v
}

func (o CheckDomainItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckDomainItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domain"] = o.Domain
	toSerialize["key"] = o.Key
	toSerialize["originKey"] = o.OriginKey
	toSerialize["value"] = o.Value
	toSerialize["status"] = o.Status
	toSerialize["statusCode"] = o.StatusCode
	return toSerialize, nil
}

func (o *CheckDomainItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"domain",
		"key",
		"originKey",
		"value",
		"status",
		"statusCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckDomainItem := _CheckDomainItem{}

	err = json.Unmarshal(data, &varCheckDomainItem, json.RejectUnknownMembers(true))

	if err != nil {
		return err
	}

	*o = CheckDomainItem(varCheckDomainItem)

	return err
}

type NullableCheckDomainItem struct {
	value *CheckDomainItem
	isSet bool
}

func (v NullableCheckDomainItem) Get() *CheckDomainItem {
	return v.value
}

func (v *NullableCheckDomainItem) Set(val *CheckDomainItem) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckDomainItem) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckDomainItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckDomainItem(val *CheckDomainItem) *NullableCheckDomainItem {
	return &NullableCheckDomainItem{value: val, isSet: true}
}

func (v NullableCheckDomainItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckDomainItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
