/*
ANSSL OpenAPI

ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package anssl

import (
	"encoding/json/v2"
	"fmt"
)

// CertificateAuthority 证书颁发机构。
type CertificateAuthority string

// List of CertificateAuthority
const (
	CERTIFICATEAUTHORITY_LETS_ENCRYPT CertificateAuthority = "LetsEncrypt"
	CERTIFICATEAUTHORITY_ZERO_SSL     CertificateAuthority = "ZeroSSL"
	CERTIFICATEAUTHORITY_GOOGLE       CertificateAuthority = "Google"
	CERTIFICATEAUTHORITY_SSL_COM      CertificateAuthority = "SSLCom"
	CERTIFICATEAUTHORITY_ACTALIS      CertificateAuthority = "Actalis"
)

// All allowed values of CertificateAuthority enum
var AllowedCertificateAuthorityEnumValues = []CertificateAuthority{
	"LetsEncrypt",
	"ZeroSSL",
	"Google",
	"SSLCom",
	"Actalis",
}

func (v *CertificateAuthority) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CertificateAuthority(value)
	for _, existing := range AllowedCertificateAuthorityEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CertificateAuthority", value)
}

// NewCertificateAuthorityFromValue returns a pointer to a valid CertificateAuthority
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCertificateAuthorityFromValue(v string) (*CertificateAuthority, error) {
	ev := CertificateAuthority(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CertificateAuthority: valid values are %v", v, AllowedCertificateAuthorityEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CertificateAuthority) IsValid() bool {
	for _, existing := range AllowedCertificateAuthorityEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CertificateAuthority value
func (v CertificateAuthority) Ptr() *CertificateAuthority {
	return &v
}

type NullableCertificateAuthority struct {
	value *CertificateAuthority
	isSet bool
}

func (v NullableCertificateAuthority) Get() *CertificateAuthority {
	return v.value
}

func (v *NullableCertificateAuthority) Set(val *CertificateAuthority) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateAuthority) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateAuthority) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateAuthority(val *CertificateAuthority) *NullableCertificateAuthority {
	return &NullableCertificateAuthority{value: val, isSet: true}
}

func (v NullableCertificateAuthority) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateAuthority) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
