/*
 * ANSSL OpenAPI
 * ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.anssl.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import cn.anssl.sdk.model.CertificateOperationStatus;
import cn.anssl.sdk.model.CertificateOperationType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import cn.anssl.sdk.ApiClient;
/**
 * CertificateOperation
 */
@JsonPropertyOrder({
  CertificateOperation.JSON_PROPERTY_REQUESTED_OPERATION_ID,
  CertificateOperation.JSON_PROPERTY_OPERATION_ID,
  CertificateOperation.JSON_PROPERTY_CERT_KEY,
  CertificateOperation.JSON_PROPERTY_TYPE,
  CertificateOperation.JSON_PROPERTY_STATUS,
  CertificateOperation.JSON_PROPERTY_REQUEST_KEY,
  CertificateOperation.JSON_PROPERTY_ATTEMPT,
  CertificateOperation.JSON_PROPERTY_MAX_ATTEMPTS,
  CertificateOperation.JSON_PROPERTY_FAILURE_REASON,
  CertificateOperation.JSON_PROPERTY_CREATED_AT,
  CertificateOperation.JSON_PROPERTY_UPDATED_AT,
  CertificateOperation.JSON_PROPERTY_STARTED_AT,
  CertificateOperation.JSON_PROPERTY_FINISHED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class CertificateOperation {
  public static final String JSON_PROPERTY_REQUESTED_OPERATION_ID = "requestedOperationId";
  @javax.annotation.Nonnull
  private String requestedOperationId;

  public static final String JSON_PROPERTY_OPERATION_ID = "operationId";
  @javax.annotation.Nonnull
  private String operationId;

  public static final String JSON_PROPERTY_CERT_KEY = "certKey";
  @javax.annotation.Nonnull
  private String certKey;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private CertificateOperationType type;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private CertificateOperationStatus status;

  public static final String JSON_PROPERTY_REQUEST_KEY = "requestKey";
  @javax.annotation.Nonnull
  private String requestKey;

  public static final String JSON_PROPERTY_ATTEMPT = "attempt";
  @javax.annotation.Nonnull
  private Integer attempt;

  public static final String JSON_PROPERTY_MAX_ATTEMPTS = "maxAttempts";
  @javax.annotation.Nonnull
  private Integer maxAttempts;

  public static final String JSON_PROPERTY_FAILURE_REASON = "failureReason";
  @javax.annotation.Nullable
  private String failureReason;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @javax.annotation.Nonnull
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_STARTED_AT = "startedAt";
  @javax.annotation.Nullable
  private OffsetDateTime startedAt;

  public static final String JSON_PROPERTY_FINISHED_AT = "finishedAt";
  @javax.annotation.Nullable
  private OffsetDateTime finishedAt;

  public CertificateOperation() { 
  }

  public CertificateOperation requestedOperationId(@javax.annotation.Nonnull String requestedOperationId) {
    this.requestedOperationId = requestedOperationId;
    return this;
  }

  /**
   * 避免跨语言 int64 精度问题的十进制字符串操作 ID。
   * @return requestedOperationId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REQUESTED_OPERATION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRequestedOperationId() {
    return requestedOperationId;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUESTED_OPERATION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequestedOperationId(@javax.annotation.Nonnull String requestedOperationId) {
    this.requestedOperationId = requestedOperationId;
  }


  public CertificateOperation operationId(@javax.annotation.Nonnull String operationId) {
    this.operationId = operationId;
    return this;
  }

  /**
   * 避免跨语言 int64 精度问题的十进制字符串操作 ID。
   * @return operationId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OPERATION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getOperationId() {
    return operationId;
  }


  @JsonProperty(value = JSON_PROPERTY_OPERATION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOperationId(@javax.annotation.Nonnull String operationId) {
    this.operationId = operationId;
  }


  public CertificateOperation certKey(@javax.annotation.Nonnull String certKey) {
    this.certKey = certKey;
    return this;
  }

  /**
   * 关联证书外部标识。
   * @return certKey
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CERT_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCertKey() {
    return certKey;
  }


  @JsonProperty(value = JSON_PROPERTY_CERT_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCertKey(@javax.annotation.Nonnull String certKey) {
    this.certKey = certKey;
  }


  public CertificateOperation type(@javax.annotation.Nonnull CertificateOperationType type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public CertificateOperationType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull CertificateOperationType type) {
    this.type = type;
  }


  public CertificateOperation status(@javax.annotation.Nonnull CertificateOperationStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public CertificateOperationStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull CertificateOperationStatus status) {
    this.status = status;
  }


  public CertificateOperation requestKey(@javax.annotation.Nonnull String requestKey) {
    this.requestKey = requestKey;
    return this;
  }

  /**
   * 实际使用的幂等键。
   * @return requestKey
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REQUEST_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRequestKey() {
    return requestKey;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUEST_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequestKey(@javax.annotation.Nonnull String requestKey) {
    this.requestKey = requestKey;
  }


  public CertificateOperation attempt(@javax.annotation.Nonnull Integer attempt) {
    this.attempt = attempt;
    return this;
  }

  /**
   * 已执行次数。
   * minimum: 0
   * @return attempt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ATTEMPT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getAttempt() {
    return attempt;
  }


  @JsonProperty(value = JSON_PROPERTY_ATTEMPT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAttempt(@javax.annotation.Nonnull Integer attempt) {
    this.attempt = attempt;
  }


  public CertificateOperation maxAttempts(@javax.annotation.Nonnull Integer maxAttempts) {
    this.maxAttempts = maxAttempts;
    return this;
  }

  /**
   * 最大执行次数。
   * minimum: 1
   * @return maxAttempts
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MAX_ATTEMPTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getMaxAttempts() {
    return maxAttempts;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_ATTEMPTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMaxAttempts(@javax.annotation.Nonnull Integer maxAttempts) {
    this.maxAttempts = maxAttempts;
  }


  public CertificateOperation failureReason(@javax.annotation.Nullable String failureReason) {
    this.failureReason = failureReason;
    return this;
  }

  /**
   * 最近失败原因。
   * @return failureReason
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FAILURE_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFailureReason() {
    return failureReason;
  }


  @JsonProperty(value = JSON_PROPERTY_FAILURE_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFailureReason(@javax.annotation.Nullable String failureReason) {
    this.failureReason = failureReason;
  }


  public CertificateOperation createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * 操作创建时间。
   * @return createdAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public CertificateOperation updatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * 操作更新时间。
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public CertificateOperation startedAt(@javax.annotation.Nullable OffsetDateTime startedAt) {
    this.startedAt = startedAt;
    return this;
  }

  /**
   * 首次开始时间。
   * @return startedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STARTED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getStartedAt() {
    return startedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_STARTED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartedAt(@javax.annotation.Nullable OffsetDateTime startedAt) {
    this.startedAt = startedAt;
  }


  public CertificateOperation finishedAt(@javax.annotation.Nullable OffsetDateTime finishedAt) {
    this.finishedAt = finishedAt;
    return this;
  }

  /**
   * 进入终态时间。
   * @return finishedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FINISHED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getFinishedAt() {
    return finishedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_FINISHED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFinishedAt(@javax.annotation.Nullable OffsetDateTime finishedAt) {
    this.finishedAt = finishedAt;
  }


  /**
   * Return true if this CertificateOperation object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificateOperation certificateOperation = (CertificateOperation) o;
    return Objects.equals(this.requestedOperationId, certificateOperation.requestedOperationId) &&
        Objects.equals(this.operationId, certificateOperation.operationId) &&
        Objects.equals(this.certKey, certificateOperation.certKey) &&
        Objects.equals(this.type, certificateOperation.type) &&
        Objects.equals(this.status, certificateOperation.status) &&
        Objects.equals(this.requestKey, certificateOperation.requestKey) &&
        Objects.equals(this.attempt, certificateOperation.attempt) &&
        Objects.equals(this.maxAttempts, certificateOperation.maxAttempts) &&
        Objects.equals(this.failureReason, certificateOperation.failureReason) &&
        Objects.equals(this.createdAt, certificateOperation.createdAt) &&
        Objects.equals(this.updatedAt, certificateOperation.updatedAt) &&
        Objects.equals(this.startedAt, certificateOperation.startedAt) &&
        Objects.equals(this.finishedAt, certificateOperation.finishedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestedOperationId, operationId, certKey, type, status, requestKey, attempt, maxAttempts, failureReason, createdAt, updatedAt, startedAt, finishedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificateOperation {\n");
    sb.append("    requestedOperationId: ").append(toIndentedString(requestedOperationId)).append("\n");
    sb.append("    operationId: ").append(toIndentedString(operationId)).append("\n");
    sb.append("    certKey: ").append(toIndentedString(certKey)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    requestKey: ").append(toIndentedString(requestKey)).append("\n");
    sb.append("    attempt: ").append(toIndentedString(attempt)).append("\n");
    sb.append("    maxAttempts: ").append(toIndentedString(maxAttempts)).append("\n");
    sb.append("    failureReason: ").append(toIndentedString(failureReason)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    finishedAt: ").append(toIndentedString(finishedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `requestedOperationId` to the URL query string
    if (getRequestedOperationId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srequestedOperationId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRequestedOperationId()))));
    }

    // add `operationId` to the URL query string
    if (getOperationId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soperationId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOperationId()))));
    }

    // add `certKey` to the URL query string
    if (getCertKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scertKey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCertKey()))));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `requestKey` to the URL query string
    if (getRequestKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srequestKey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRequestKey()))));
    }

    // add `attempt` to the URL query string
    if (getAttempt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sattempt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAttempt()))));
    }

    // add `maxAttempts` to the URL query string
    if (getMaxAttempts() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smaxAttempts%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMaxAttempts()))));
    }

    // add `failureReason` to the URL query string
    if (getFailureReason() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfailureReason%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFailureReason()))));
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `updatedAt` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedAt()))));
    }

    // add `startedAt` to the URL query string
    if (getStartedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstartedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStartedAt()))));
    }

    // add `finishedAt` to the URL query string
    if (getFinishedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfinishedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFinishedAt()))));
    }

    return joiner.toString();
  }
}

