/*
 * ANSSL OpenAPI
 * ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.anssl.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import cn.anssl.sdk.model.CertificateAuthority;
import cn.anssl.sdk.model.CertificateKeyAlgorithm;
import cn.anssl.sdk.model.CertificateStatus;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import cn.anssl.sdk.ApiClient;
/**
 * CertificateDetail
 */
@JsonPropertyOrder({
  CertificateDetail.JSON_PROPERTY_CERT_KEY,
  CertificateDetail.JSON_PROPERTY_STATUS,
  CertificateDetail.JSON_PROPERTY_DOMAINS,
  CertificateDetail.JSON_PROPERTY_CA,
  CertificateDetail.JSON_PROPERTY_KEY_ALGORITHM,
  CertificateDetail.JSON_PROPERTY_NOT_BEFORE,
  CertificateDetail.JSON_PROPERTY_NOT_AFTER,
  CertificateDetail.JSON_PROPERTY_DAYS_LEFT,
  CertificateDetail.JSON_PROPERTY_FAILURE_REASON,
  CertificateDetail.JSON_PROPERTY_CREATED_AT,
  CertificateDetail.JSON_PROPERTY_UPDATED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class CertificateDetail {
  public static final String JSON_PROPERTY_CERT_KEY = "certKey";
  @javax.annotation.Nonnull
  private String certKey;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private CertificateStatus status;

  public static final String JSON_PROPERTY_DOMAINS = "domains";
  @javax.annotation.Nonnull
  private List<String> domains = new ArrayList<>();

  public static final String JSON_PROPERTY_CA = "ca";
  @javax.annotation.Nonnull
  private CertificateAuthority ca;

  public static final String JSON_PROPERTY_KEY_ALGORITHM = "keyAlgorithm";
  @javax.annotation.Nonnull
  private CertificateKeyAlgorithm keyAlgorithm;

  public static final String JSON_PROPERTY_NOT_BEFORE = "notBefore";
  @javax.annotation.Nullable
  private OffsetDateTime notBefore;

  public static final String JSON_PROPERTY_NOT_AFTER = "notAfter";
  @javax.annotation.Nullable
  private OffsetDateTime notAfter;

  public static final String JSON_PROPERTY_DAYS_LEFT = "daysLeft";
  @javax.annotation.Nullable
  private Integer daysLeft;

  public static final String JSON_PROPERTY_FAILURE_REASON = "failureReason";
  @javax.annotation.Nullable
  private String failureReason;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @javax.annotation.Nonnull
  private OffsetDateTime updatedAt;

  public CertificateDetail() { 
  }

  public CertificateDetail certKey(@javax.annotation.Nonnull String certKey) {
    this.certKey = certKey;
    return this;
  }

  /**
   * 证书外部唯一标识。
   * @return certKey
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CERT_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCertKey() {
    return certKey;
  }


  @JsonProperty(value = JSON_PROPERTY_CERT_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCertKey(@javax.annotation.Nonnull String certKey) {
    this.certKey = certKey;
  }


  public CertificateDetail status(@javax.annotation.Nonnull CertificateStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public CertificateStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull CertificateStatus status) {
    this.status = status;
  }


  public CertificateDetail domains(@javax.annotation.Nonnull List<String> domains) {
    this.domains = domains;
    return this;
  }

  public CertificateDetail addDomainsItem(String domainsItem) {
    if (this.domains == null) {
      this.domains = new ArrayList<>();
    }
    this.domains.add(domainsItem);
    return this;
  }

  /**
   * 证书域名列表。
   * @return domains
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DOMAINS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getDomains() {
    return domains;
  }


  @JsonProperty(value = JSON_PROPERTY_DOMAINS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDomains(@javax.annotation.Nonnull List<String> domains) {
    this.domains = domains;
  }


  public CertificateDetail ca(@javax.annotation.Nonnull CertificateAuthority ca) {
    this.ca = ca;
    return this;
  }

  /**
   * Get ca
   * @return ca
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public CertificateAuthority getCa() {
    return ca;
  }


  @JsonProperty(value = JSON_PROPERTY_CA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCa(@javax.annotation.Nonnull CertificateAuthority ca) {
    this.ca = ca;
  }


  public CertificateDetail keyAlgorithm(@javax.annotation.Nonnull CertificateKeyAlgorithm keyAlgorithm) {
    this.keyAlgorithm = keyAlgorithm;
    return this;
  }

  /**
   * Get keyAlgorithm
   * @return keyAlgorithm
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEY_ALGORITHM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public CertificateKeyAlgorithm getKeyAlgorithm() {
    return keyAlgorithm;
  }


  @JsonProperty(value = JSON_PROPERTY_KEY_ALGORITHM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKeyAlgorithm(@javax.annotation.Nonnull CertificateKeyAlgorithm keyAlgorithm) {
    this.keyAlgorithm = keyAlgorithm;
  }


  public CertificateDetail notBefore(@javax.annotation.Nullable OffsetDateTime notBefore) {
    this.notBefore = notBefore;
    return this;
  }

  /**
   * 证书生效时间。
   * @return notBefore
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NOT_BEFORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getNotBefore() {
    return notBefore;
  }


  @JsonProperty(value = JSON_PROPERTY_NOT_BEFORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotBefore(@javax.annotation.Nullable OffsetDateTime notBefore) {
    this.notBefore = notBefore;
  }


  public CertificateDetail notAfter(@javax.annotation.Nullable OffsetDateTime notAfter) {
    this.notAfter = notAfter;
    return this;
  }

  /**
   * 证书过期时间。
   * @return notAfter
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NOT_AFTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getNotAfter() {
    return notAfter;
  }


  @JsonProperty(value = JSON_PROPERTY_NOT_AFTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotAfter(@javax.annotation.Nullable OffsetDateTime notAfter) {
    this.notAfter = notAfter;
  }


  public CertificateDetail daysLeft(@javax.annotation.Nullable Integer daysLeft) {
    this.daysLeft = daysLeft;
    return this;
  }

  /**
   * 剩余有效天数。
   * @return daysLeft
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DAYS_LEFT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getDaysLeft() {
    return daysLeft;
  }


  @JsonProperty(value = JSON_PROPERTY_DAYS_LEFT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDaysLeft(@javax.annotation.Nullable Integer daysLeft) {
    this.daysLeft = daysLeft;
  }


  public CertificateDetail failureReason(@javax.annotation.Nullable String failureReason) {
    this.failureReason = failureReason;
    return this;
  }

  /**
   * 最近失败原因。
   * @return failureReason
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FAILURE_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFailureReason() {
    return failureReason;
  }


  @JsonProperty(value = JSON_PROPERTY_FAILURE_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFailureReason(@javax.annotation.Nullable String failureReason) {
    this.failureReason = failureReason;
  }


  public CertificateDetail createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * 记录创建时间。
   * @return createdAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public CertificateDetail updatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * 记录更新时间。
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  /**
   * Return true if this CertificateDetail object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificateDetail certificateDetail = (CertificateDetail) o;
    return Objects.equals(this.certKey, certificateDetail.certKey) &&
        Objects.equals(this.status, certificateDetail.status) &&
        Objects.equals(this.domains, certificateDetail.domains) &&
        Objects.equals(this.ca, certificateDetail.ca) &&
        Objects.equals(this.keyAlgorithm, certificateDetail.keyAlgorithm) &&
        Objects.equals(this.notBefore, certificateDetail.notBefore) &&
        Objects.equals(this.notAfter, certificateDetail.notAfter) &&
        Objects.equals(this.daysLeft, certificateDetail.daysLeft) &&
        Objects.equals(this.failureReason, certificateDetail.failureReason) &&
        Objects.equals(this.createdAt, certificateDetail.createdAt) &&
        Objects.equals(this.updatedAt, certificateDetail.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certKey, status, domains, ca, keyAlgorithm, notBefore, notAfter, daysLeft, failureReason, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificateDetail {\n");
    sb.append("    certKey: ").append(toIndentedString(certKey)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    domains: ").append(toIndentedString(domains)).append("\n");
    sb.append("    ca: ").append(toIndentedString(ca)).append("\n");
    sb.append("    keyAlgorithm: ").append(toIndentedString(keyAlgorithm)).append("\n");
    sb.append("    notBefore: ").append(toIndentedString(notBefore)).append("\n");
    sb.append("    notAfter: ").append(toIndentedString(notAfter)).append("\n");
    sb.append("    daysLeft: ").append(toIndentedString(daysLeft)).append("\n");
    sb.append("    failureReason: ").append(toIndentedString(failureReason)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `certKey` to the URL query string
    if (getCertKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scertKey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCertKey()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `domains` to the URL query string
    if (getDomains() != null) {
      for (int i = 0; i < getDomains().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdomains%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getDomains().get(i)))));
      }
    }

    // add `ca` to the URL query string
    if (getCa() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sca%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCa()))));
    }

    // add `keyAlgorithm` to the URL query string
    if (getKeyAlgorithm() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%skeyAlgorithm%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKeyAlgorithm()))));
    }

    // add `notBefore` to the URL query string
    if (getNotBefore() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snotBefore%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNotBefore()))));
    }

    // add `notAfter` to the URL query string
    if (getNotAfter() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snotAfter%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNotAfter()))));
    }

    // add `daysLeft` to the URL query string
    if (getDaysLeft() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdaysLeft%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDaysLeft()))));
    }

    // add `failureReason` to the URL query string
    if (getFailureReason() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfailureReason%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFailureReason()))));
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `updatedAt` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedAt()))));
    }

    return joiner.toString();
  }
}

