/*
 * ANSSL OpenAPI
 * ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.anssl.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import cn.anssl.sdk.ApiClient;
/**
 * DeleteCertificateRequest
 */
@JsonPropertyOrder({
  DeleteCertificateRequest.JSON_PROPERTY_ACTION,
  DeleteCertificateRequest.JSON_PROPERTY_CERT_KEY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class DeleteCertificateRequest {
  /**
   * 固定为 delete。
   */
  public enum ActionEnum {
    DELETE(String.valueOf("delete"));

    private String value;

    ActionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ActionEnum fromValue(String value) {
      for (ActionEnum b : ActionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACTION = "action";
  @javax.annotation.Nonnull
  private ActionEnum action;

  public static final String JSON_PROPERTY_CERT_KEY = "certKey";
  @javax.annotation.Nonnull
  private String certKey;

  public DeleteCertificateRequest() { 
  }

  public DeleteCertificateRequest action(@javax.annotation.Nonnull ActionEnum action) {
    this.action = action;
    return this;
  }

  /**
   * 固定为 delete。
   * @return action
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ACTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ActionEnum getAction() {
    return action;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAction(@javax.annotation.Nonnull ActionEnum action) {
    this.action = action;
  }


  public DeleteCertificateRequest certKey(@javax.annotation.Nonnull String certKey) {
    this.certKey = certKey;
    return this;
  }

  /**
   * 要删除的平台证书标识。
   * @return certKey
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CERT_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCertKey() {
    return certKey;
  }


  @JsonProperty(value = JSON_PROPERTY_CERT_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCertKey(@javax.annotation.Nonnull String certKey) {
    this.certKey = certKey;
  }


  /**
   * Return true if this DeleteCertificateRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteCertificateRequest deleteCertificateRequest = (DeleteCertificateRequest) o;
    return Objects.equals(this.action, deleteCertificateRequest.action) &&
        Objects.equals(this.certKey, deleteCertificateRequest.certKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, certKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteCertificateRequest {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    certKey: ").append(toIndentedString(certKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `action` to the URL query string
    if (getAction() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saction%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAction()))));
    }

    // add `certKey` to the URL query string
    if (getCertKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scertKey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCertKey()))));
    }

    return joiner.toString();
  }
}

