/*
 * ANSSL OpenAPI
 * ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.anssl.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import cn.anssl.sdk.model.ApplyCertificateRequest;
import cn.anssl.sdk.model.CertificateAuthority;
import cn.anssl.sdk.model.CertificateKeyAlgorithm;
import cn.anssl.sdk.model.DeleteCertificateRequest;
import cn.anssl.sdk.model.RenewCertificateRequest;
import cn.anssl.sdk.model.RevokeCertificateRequest;
import cn.anssl.sdk.model.VerificationType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import cn.anssl.sdk.ApiClient;
import cn.anssl.sdk.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
@JsonDeserialize(using = SubmitCertificateActionRequest.SubmitCertificateActionRequestDeserializer.class)
@JsonSerialize(using = SubmitCertificateActionRequest.SubmitCertificateActionRequestSerializer.class)
public class SubmitCertificateActionRequest extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(SubmitCertificateActionRequest.class.getName());

    public static class SubmitCertificateActionRequestSerializer extends StdSerializer<SubmitCertificateActionRequest> {
        public SubmitCertificateActionRequestSerializer(Class<SubmitCertificateActionRequest> t) {
            super(t);
        }

        public SubmitCertificateActionRequestSerializer() {
            this(null);
        }

        @Override
        public void serialize(SubmitCertificateActionRequest value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class SubmitCertificateActionRequestDeserializer extends StdDeserializer<SubmitCertificateActionRequest> {
        public SubmitCertificateActionRequestDeserializer() {
            this(SubmitCertificateActionRequest.class);
        }

        public SubmitCertificateActionRequestDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public SubmitCertificateActionRequest deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = ctxt.readTree(jp);
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize ApplyCertificateRequest
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (ApplyCertificateRequest.class.equals(Integer.class) || ApplyCertificateRequest.class.equals(Long.class) || ApplyCertificateRequest.class.equals(Float.class) || ApplyCertificateRequest.class.equals(Double.class) || ApplyCertificateRequest.class.equals(Boolean.class) || ApplyCertificateRequest.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((ApplyCertificateRequest.class.equals(Integer.class) || ApplyCertificateRequest.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((ApplyCertificateRequest.class.equals(Float.class) || ApplyCertificateRequest.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (ApplyCertificateRequest.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (ApplyCertificateRequest.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(ApplyCertificateRequest.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'ApplyCertificateRequest'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'ApplyCertificateRequest'", e);
            }

            // deserialize DeleteCertificateRequest
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (DeleteCertificateRequest.class.equals(Integer.class) || DeleteCertificateRequest.class.equals(Long.class) || DeleteCertificateRequest.class.equals(Float.class) || DeleteCertificateRequest.class.equals(Double.class) || DeleteCertificateRequest.class.equals(Boolean.class) || DeleteCertificateRequest.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((DeleteCertificateRequest.class.equals(Integer.class) || DeleteCertificateRequest.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((DeleteCertificateRequest.class.equals(Float.class) || DeleteCertificateRequest.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (DeleteCertificateRequest.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (DeleteCertificateRequest.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(DeleteCertificateRequest.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'DeleteCertificateRequest'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'DeleteCertificateRequest'", e);
            }

            // deserialize RenewCertificateRequest
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (RenewCertificateRequest.class.equals(Integer.class) || RenewCertificateRequest.class.equals(Long.class) || RenewCertificateRequest.class.equals(Float.class) || RenewCertificateRequest.class.equals(Double.class) || RenewCertificateRequest.class.equals(Boolean.class) || RenewCertificateRequest.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((RenewCertificateRequest.class.equals(Integer.class) || RenewCertificateRequest.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((RenewCertificateRequest.class.equals(Float.class) || RenewCertificateRequest.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (RenewCertificateRequest.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (RenewCertificateRequest.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(RenewCertificateRequest.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'RenewCertificateRequest'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'RenewCertificateRequest'", e);
            }

            // deserialize RevokeCertificateRequest
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (RevokeCertificateRequest.class.equals(Integer.class) || RevokeCertificateRequest.class.equals(Long.class) || RevokeCertificateRequest.class.equals(Float.class) || RevokeCertificateRequest.class.equals(Double.class) || RevokeCertificateRequest.class.equals(Boolean.class) || RevokeCertificateRequest.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((RevokeCertificateRequest.class.equals(Integer.class) || RevokeCertificateRequest.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((RevokeCertificateRequest.class.equals(Float.class) || RevokeCertificateRequest.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (RevokeCertificateRequest.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (RevokeCertificateRequest.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(RevokeCertificateRequest.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'RevokeCertificateRequest'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'RevokeCertificateRequest'", e);
            }

            if (match == 1) {
                SubmitCertificateActionRequest ret = new SubmitCertificateActionRequest();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format(java.util.Locale.ROOT, "Failed deserialization for SubmitCertificateActionRequest: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public SubmitCertificateActionRequest getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "SubmitCertificateActionRequest cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public SubmitCertificateActionRequest() {
        super("oneOf", Boolean.FALSE);
    }

    public SubmitCertificateActionRequest(ApplyCertificateRequest o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public SubmitCertificateActionRequest(DeleteCertificateRequest o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public SubmitCertificateActionRequest(RenewCertificateRequest o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public SubmitCertificateActionRequest(RevokeCertificateRequest o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("ApplyCertificateRequest", ApplyCertificateRequest.class);
        schemas.put("DeleteCertificateRequest", DeleteCertificateRequest.class);
        schemas.put("RenewCertificateRequest", RenewCertificateRequest.class);
        schemas.put("RevokeCertificateRequest", RevokeCertificateRequest.class);
        JSON.registerDescendants(SubmitCertificateActionRequest.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return SubmitCertificateActionRequest.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * ApplyCertificateRequest, DeleteCertificateRequest, RenewCertificateRequest, RevokeCertificateRequest
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(ApplyCertificateRequest.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(DeleteCertificateRequest.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(RenewCertificateRequest.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(RevokeCertificateRequest.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be ApplyCertificateRequest, DeleteCertificateRequest, RenewCertificateRequest, RevokeCertificateRequest");
    }

    /**
     * Get the actual instance, which can be the following:
     * ApplyCertificateRequest, DeleteCertificateRequest, RenewCertificateRequest, RevokeCertificateRequest
     *
     * @return The actual instance (ApplyCertificateRequest, DeleteCertificateRequest, RenewCertificateRequest, RevokeCertificateRequest)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `ApplyCertificateRequest`. If the actual instance is not `ApplyCertificateRequest`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `ApplyCertificateRequest`
     * @throws ClassCastException if the instance is not `ApplyCertificateRequest`
     */
    public ApplyCertificateRequest getApplyCertificateRequest() throws ClassCastException {
        return (ApplyCertificateRequest)super.getActualInstance();
    }

    /**
     * Get the actual instance of `DeleteCertificateRequest`. If the actual instance is not `DeleteCertificateRequest`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DeleteCertificateRequest`
     * @throws ClassCastException if the instance is not `DeleteCertificateRequest`
     */
    public DeleteCertificateRequest getDeleteCertificateRequest() throws ClassCastException {
        return (DeleteCertificateRequest)super.getActualInstance();
    }

    /**
     * Get the actual instance of `RenewCertificateRequest`. If the actual instance is not `RenewCertificateRequest`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `RenewCertificateRequest`
     * @throws ClassCastException if the instance is not `RenewCertificateRequest`
     */
    public RenewCertificateRequest getRenewCertificateRequest() throws ClassCastException {
        return (RenewCertificateRequest)super.getActualInstance();
    }

    /**
     * Get the actual instance of `RevokeCertificateRequest`. If the actual instance is not `RevokeCertificateRequest`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `RevokeCertificateRequest`
     * @throws ClassCastException if the instance is not `RevokeCertificateRequest`
     */
    public RevokeCertificateRequest getRevokeCertificateRequest() throws ClassCastException {
        return (RevokeCertificateRequest)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof ApplyCertificateRequest) {
        if (getActualInstance() != null) {
          joiner.add(((ApplyCertificateRequest)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof RenewCertificateRequest) {
        if (getActualInstance() != null) {
          joiner.add(((RenewCertificateRequest)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof RevokeCertificateRequest) {
        if (getActualInstance() != null) {
          joiner.add(((RevokeCertificateRequest)getActualInstance()).toUrlQueryString(prefix + "one_of_2" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof DeleteCertificateRequest) {
        if (getActualInstance() != null) {
          joiner.add(((DeleteCertificateRequest)getActualInstance()).toUrlQueryString(prefix + "one_of_3" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

