/*
 * ANSSL OpenAPI
 *
 * ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Anssl.Client.FileParameter;
using OpenAPIDateConverter = Anssl.Client.OpenAPIDateConverter;

namespace Anssl.Model
{
    /// <summary>
    /// ApplyCertificateRequest
    /// </summary>
    [DataContract(Name = "ApplyCertificateRequest")]
    public partial class ApplyCertificateRequest : IValidatableObject
    {
        /// <summary>
        /// 省略时默认为 apply。
        /// </summary>
        /// <value>省略时默认为 apply。</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ActionEnum
        {
            /// <summary>
            /// Enum Apply for value: apply
            /// </summary>
            [EnumMember(Value = "apply")]
            Apply = 1
        }


        /// <summary>
        /// 省略时默认为 apply。
        /// </summary>
        /// <value>省略时默认为 apply。</value>
        [DataMember(Name = "action", EmitDefaultValue = false)]
        public ActionEnum? Action { get; set; }

        /// <summary>
        /// Gets or Sets Ca
        /// </summary>
        [DataMember(Name = "ca", EmitDefaultValue = false)]
        public CertificateAuthority? Ca { get; set; }

        /// <summary>
        /// Gets or Sets KeyAlgorithm
        /// </summary>
        [DataMember(Name = "keyAlgorithm", EmitDefaultValue = false)]
        public CertificateKeyAlgorithm? KeyAlgorithm { get; set; }

        /// <summary>
        /// Gets or Sets VerificationType
        /// </summary>
        [DataMember(Name = "verificationType", EmitDefaultValue = false)]
        public VerificationType? VerificationType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApplyCertificateRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ApplyCertificateRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApplyCertificateRequest" /> class.
        /// </summary>
        /// <param name="action">省略时默认为 apply。 (default to ActionEnum.Apply).</param>
        /// <param name="domains">非空且不重复的域名列表，最多 100 项。 (required).</param>
        /// <param name="ca">ca.</param>
        /// <param name="keyAlgorithm">keyAlgorithm.</param>
        /// <param name="verificationType">verificationType.</param>
        /// <param name="requestKey">用户范围内的可选幂等键；省略时由服务端生成。.</param>
        public ApplyCertificateRequest(ActionEnum? action = ActionEnum.Apply, List<string> domains = default, CertificateAuthority? ca = default, CertificateKeyAlgorithm? keyAlgorithm = default, VerificationType? verificationType = default, string requestKey = default)
        {
            // to ensure "domains" is required (not null)
            if (domains == null)
            {
                throw new ArgumentNullException("domains is a required property for ApplyCertificateRequest and cannot be null");
            }
            this.Domains = domains;
            this.Action = action;
            this.Ca = ca;
            this.KeyAlgorithm = keyAlgorithm;
            this.VerificationType = verificationType;
            this.RequestKey = requestKey;
        }

        /// <summary>
        /// 非空且不重复的域名列表，最多 100 项。
        /// </summary>
        /// <value>非空且不重复的域名列表，最多 100 项。</value>
        [DataMember(Name = "domains", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Domains { get; set; }

        /// <summary>
        /// 用户范围内的可选幂等键；省略时由服务端生成。
        /// </summary>
        /// <value>用户范围内的可选幂等键；省略时由服务端生成。</value>
        [DataMember(Name = "requestKey", EmitDefaultValue = false)]
        public string RequestKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApplyCertificateRequest {\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  Domains: ").Append(Domains).Append("\n");
            sb.Append("  Ca: ").Append(Ca).Append("\n");
            sb.Append("  KeyAlgorithm: ").Append(KeyAlgorithm).Append("\n");
            sb.Append("  VerificationType: ").Append(VerificationType).Append("\n");
            sb.Append("  RequestKey: ").Append(RequestKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // RequestKey (string) maxLength
            if (this.RequestKey != null && this.RequestKey.Length > 128)
            {
                yield return new ValidationResult("Invalid value for RequestKey, length must be less than 128.", new [] { "RequestKey" });
            }

            // RequestKey (string) minLength
            if (this.RequestKey != null && this.RequestKey.Length < 1)
            {
                yield return new ValidationResult("Invalid value for RequestKey, length must be greater than 1.", new [] { "RequestKey" });
            }

            yield break;
        }
    }

}
