/*
 * ANSSL OpenAPI
 *
 * ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Anssl.Client.FileParameter;
using OpenAPIDateConverter = Anssl.Client.OpenAPIDateConverter;

namespace Anssl.Model
{
    /// <summary>
    /// 证书颁发机构。
    /// </summary>
    /// <value>证书颁发机构。</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CertificateAuthority
    {
        /// <summary>
        /// Enum LetsEncrypt for value: LetsEncrypt
        /// </summary>
        [EnumMember(Value = "LetsEncrypt")]
        LetsEncrypt = 1,

        /// <summary>
        /// Enum ZeroSSL for value: ZeroSSL
        /// </summary>
        [EnumMember(Value = "ZeroSSL")]
        ZeroSSL = 2,

        /// <summary>
        /// Enum Google for value: Google
        /// </summary>
        [EnumMember(Value = "Google")]
        Google = 3,

        /// <summary>
        /// Enum SSLCom for value: SSLCom
        /// </summary>
        [EnumMember(Value = "SSLCom")]
        SSLCom = 4,

        /// <summary>
        /// Enum Actalis for value: Actalis
        /// </summary>
        [EnumMember(Value = "Actalis")]
        Actalis = 5
    }

}
