/*
 * ANSSL OpenAPI
 *
 * ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Anssl.Client.FileParameter;
using OpenAPIDateConverter = Anssl.Client.OpenAPIDateConverter;

namespace Anssl.Model
{
    /// <summary>
    /// CertificateDownload
    /// </summary>
    [DataContract(Name = "CertificateDownload")]
    public partial class CertificateDownload : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CertificateDownload" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CertificateDownload() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CertificateDownload" /> class.
        /// </summary>
        /// <param name="domain">证书主域名。 (required).</param>
        /// <param name="certificate">叶证书 PEM。 (required).</param>
        /// <param name="privateKey">私钥 PEM。 (required).</param>
        /// <param name="issuerCertificate">CA 中间证书 PEM。.</param>
        /// <param name="fullChain">完整证书链 PEM。 (required).</param>
        public CertificateDownload(string domain = default, string certificate = default, string privateKey = default, string issuerCertificate = default, string fullChain = default)
        {
            // to ensure "domain" is required (not null)
            if (domain == null)
            {
                throw new ArgumentNullException("domain is a required property for CertificateDownload and cannot be null");
            }
            this.Domain = domain;
            // to ensure "certificate" is required (not null)
            if (certificate == null)
            {
                throw new ArgumentNullException("certificate is a required property for CertificateDownload and cannot be null");
            }
            this.Certificate = certificate;
            // to ensure "privateKey" is required (not null)
            if (privateKey == null)
            {
                throw new ArgumentNullException("privateKey is a required property for CertificateDownload and cannot be null");
            }
            this.PrivateKey = privateKey;
            // to ensure "fullChain" is required (not null)
            if (fullChain == null)
            {
                throw new ArgumentNullException("fullChain is a required property for CertificateDownload and cannot be null");
            }
            this.FullChain = fullChain;
            this.IssuerCertificate = issuerCertificate;
        }

        /// <summary>
        /// 证书主域名。
        /// </summary>
        /// <value>证书主域名。</value>
        [DataMember(Name = "domain", IsRequired = true, EmitDefaultValue = true)]
        public string Domain { get; set; }

        /// <summary>
        /// 叶证书 PEM。
        /// </summary>
        /// <value>叶证书 PEM。</value>
        [DataMember(Name = "certificate", IsRequired = true, EmitDefaultValue = true)]
        public string Certificate { get; set; }

        /// <summary>
        /// 私钥 PEM。
        /// </summary>
        /// <value>私钥 PEM。</value>
        [DataMember(Name = "privateKey", IsRequired = true, EmitDefaultValue = true)]
        public string PrivateKey { get; set; }

        /// <summary>
        /// CA 中间证书 PEM。
        /// </summary>
        /// <value>CA 中间证书 PEM。</value>
        [DataMember(Name = "issuerCertificate", EmitDefaultValue = false)]
        public string IssuerCertificate { get; set; }

        /// <summary>
        /// 完整证书链 PEM。
        /// </summary>
        /// <value>完整证书链 PEM。</value>
        [DataMember(Name = "fullChain", IsRequired = true, EmitDefaultValue = true)]
        public string FullChain { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CertificateDownload {\n");
            sb.Append("  Domain: ").Append(Domain).Append("\n");
            sb.Append("  Certificate: ").Append(Certificate).Append("\n");
            sb.Append("  PrivateKey: ").Append(PrivateKey).Append("\n");
            sb.Append("  IssuerCertificate: ").Append(IssuerCertificate).Append("\n");
            sb.Append("  FullChain: ").Append(FullChain).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
