/*
 * ANSSL OpenAPI
 *
 * ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Anssl.Client.FileParameter;
using OpenAPIDateConverter = Anssl.Client.OpenAPIDateConverter;

namespace Anssl.Model
{
    /// <summary>
    /// 生命周期请求受理后的提示状态。
    /// </summary>
    /// <value>生命周期请求受理后的提示状态。</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CertificateActionStatus
    {
        /// <summary>
        /// Enum Applying for value: applying
        /// </summary>
        [EnumMember(Value = "applying")]
        Applying = 1,

        /// <summary>
        /// Enum Renewing for value: renewing
        /// </summary>
        [EnumMember(Value = "renewing")]
        Renewing = 2,

        /// <summary>
        /// Enum Revoking for value: revoking
        /// </summary>
        [EnumMember(Value = "revoking")]
        Revoking = 3,

        /// <summary>
        /// Enum Deleted for value: deleted
        /// </summary>
        [EnumMember(Value = "deleted")]
        Deleted = 4
    }

}
