/*
 * ANSSL OpenAPI
 *
 * ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Anssl.Client.FileParameter;
using OpenAPIDateConverter = Anssl.Client.OpenAPIDateConverter;

namespace Anssl.Model
{
    /// <summary>
    /// CheckDomainData
    /// </summary>
    [DataContract(Name = "CheckDomainData")]
    public partial class CheckDomainData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckDomainData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CheckDomainData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckDomainData" /> class.
        /// </summary>
        /// <param name="cnames">CNAME 检查结果列表。 (required).</param>
        public CheckDomainData(List<CheckDomainItem> cnames = default)
        {
            // to ensure "cnames" is required (not null)
            if (cnames == null)
            {
                throw new ArgumentNullException("cnames is a required property for CheckDomainData and cannot be null");
            }
            this.Cnames = cnames;
        }

        /// <summary>
        /// CNAME 检查结果列表。
        /// </summary>
        /// <value>CNAME 检查结果列表。</value>
        [DataMember(Name = "cnames", IsRequired = true, EmitDefaultValue = true)]
        public List<CheckDomainItem> Cnames { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CheckDomainData {\n");
            sb.Append("  Cnames: ").Append(Cnames).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
