/*
 * ANSSL OpenAPI
 *
 * ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Anssl.Client.FileParameter;
using OpenAPIDateConverter = Anssl.Client.OpenAPIDateConverter;

namespace Anssl.Model
{
    /// <summary>
    /// CheckDomainItem
    /// </summary>
    [DataContract(Name = "CheckDomainItem")]
    public partial class CheckDomainItem : IValidatableObject
    {
        /// <summary>
        /// 可读解析状态。
        /// </summary>
        /// <value>可读解析状态。</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Unknown for value: unknown
            /// </summary>
            [EnumMember(Value = "unknown")]
            Unknown,

            /// <summary>
            /// Enum Normal for value: normal
            /// </summary>
            [EnumMember(Value = "normal")]
            Normal,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            [EnumMember(Value = "failed")]
            Failed
        }


        /// <summary>
        /// 可读解析状态。
        /// </summary>
        /// <value>可读解析状态。</value>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// 0 未知、1 正常、2 失败。
        /// </summary>
        /// <value>0 未知、1 正常、2 失败。</value>
        public enum StatusCodeEnum
        {
            /// <summary>
            /// Enum NUMBER_0 for value: 0
            /// </summary>
            NUMBER_0 = 0,

            /// <summary>
            /// Enum NUMBER_1 for value: 1
            /// </summary>
            NUMBER_1 = 1,

            /// <summary>
            /// Enum NUMBER_2 for value: 2
            /// </summary>
            NUMBER_2 = 2
        }


        /// <summary>
        /// 0 未知、1 正常、2 失败。
        /// </summary>
        /// <value>0 未知、1 正常、2 失败。</value>
        [DataMember(Name = "statusCode", IsRequired = true, EmitDefaultValue = true)]
        public StatusCodeEnum StatusCode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckDomainItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CheckDomainItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckDomainItem" /> class.
        /// </summary>
        /// <param name="domain">被检查的域名。 (required).</param>
        /// <param name="key">CNAME 记录名。 (required).</param>
        /// <param name="originKey">原始 challenge 记录名。 (required).</param>
        /// <param name="value">CNAME 目标值。 (required).</param>
        /// <param name="status">可读解析状态。 (required).</param>
        /// <param name="statusCode">0 未知、1 正常、2 失败。 (required).</param>
        public CheckDomainItem(string domain = default, string key = default, string originKey = default, string value = default, StatusEnum status = default, StatusCodeEnum statusCode = default)
        {
            // to ensure "domain" is required (not null)
            if (domain == null)
            {
                throw new ArgumentNullException("domain is a required property for CheckDomainItem and cannot be null");
            }
            this.Domain = domain;
            // to ensure "key" is required (not null)
            if (key == null)
            {
                throw new ArgumentNullException("key is a required property for CheckDomainItem and cannot be null");
            }
            this.Key = key;
            // to ensure "originKey" is required (not null)
            if (originKey == null)
            {
                throw new ArgumentNullException("originKey is a required property for CheckDomainItem and cannot be null");
            }
            this.OriginKey = originKey;
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for CheckDomainItem and cannot be null");
            }
            this.Value = value;
            this.Status = status;
            this.StatusCode = statusCode;
        }

        /// <summary>
        /// 被检查的域名。
        /// </summary>
        /// <value>被检查的域名。</value>
        [DataMember(Name = "domain", IsRequired = true, EmitDefaultValue = true)]
        public string Domain { get; set; }

        /// <summary>
        /// CNAME 记录名。
        /// </summary>
        /// <value>CNAME 记录名。</value>
        [DataMember(Name = "key", IsRequired = true, EmitDefaultValue = true)]
        public string Key { get; set; }

        /// <summary>
        /// 原始 challenge 记录名。
        /// </summary>
        /// <value>原始 challenge 记录名。</value>
        [DataMember(Name = "originKey", IsRequired = true, EmitDefaultValue = true)]
        public string OriginKey { get; set; }

        /// <summary>
        /// CNAME 目标值。
        /// </summary>
        /// <value>CNAME 目标值。</value>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CheckDomainItem {\n");
            sb.Append("  Domain: ").Append(Domain).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  OriginKey: ").Append(OriginKey).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  StatusCode: ").Append(StatusCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
