/*
 * ANSSL OpenAPI
 *
 * ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Anssl.Client.FileParameter;
using OpenAPIDateConverter = Anssl.Client.OpenAPIDateConverter;

namespace Anssl.Model
{
    /// <summary>
    /// CheckDomainRequest
    /// </summary>
    [DataContract(Name = "CheckDomainRequest")]
    public partial class CheckDomainRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckDomainRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CheckDomainRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckDomainRequest" /> class.
        /// </summary>
        /// <param name="certKey">可选关联证书标识。.</param>
        /// <param name="domains">非空且不重复的域名列表，最多 100 项。 (required).</param>
        public CheckDomainRequest(string certKey = default, List<string> domains = default)
        {
            // to ensure "domains" is required (not null)
            if (domains == null)
            {
                throw new ArgumentNullException("domains is a required property for CheckDomainRequest and cannot be null");
            }
            this.Domains = domains;
            this.CertKey = certKey;
        }

        /// <summary>
        /// 可选关联证书标识。
        /// </summary>
        /// <value>可选关联证书标识。</value>
        [DataMember(Name = "certKey", EmitDefaultValue = false)]
        public string CertKey { get; set; }

        /// <summary>
        /// 非空且不重复的域名列表，最多 100 项。
        /// </summary>
        /// <value>非空且不重复的域名列表，最多 100 项。</value>
        [DataMember(Name = "domains", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Domains { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CheckDomainRequest {\n");
            sb.Append("  CertKey: ").Append(CertKey).Append("\n");
            sb.Append("  Domains: ").Append(Domains).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CertKey (string) minLength
            if (this.CertKey != null && this.CertKey.Length < 1)
            {
                yield return new ValidationResult("Invalid value for CertKey, length must be greater than 1.", new [] { "CertKey" });
            }

            yield break;
        }
    }

}
