/*
 * ANSSL OpenAPI
 *
 * ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Anssl.Client.FileParameter;
using OpenAPIDateConverter = Anssl.Client.OpenAPIDateConverter;

namespace Anssl.Model
{
    /// <summary>
    /// DeleteCertificateRequest
    /// </summary>
    [DataContract(Name = "DeleteCertificateRequest")]
    public partial class DeleteCertificateRequest : IValidatableObject
    {
        /// <summary>
        /// 固定为 delete。
        /// </summary>
        /// <value>固定为 delete。</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ActionEnum
        {
            /// <summary>
            /// Enum Delete for value: delete
            /// </summary>
            [EnumMember(Value = "delete")]
            Delete = 1
        }


        /// <summary>
        /// 固定为 delete。
        /// </summary>
        /// <value>固定为 delete。</value>
        [DataMember(Name = "action", IsRequired = true, EmitDefaultValue = true)]
        public ActionEnum Action { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DeleteCertificateRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DeleteCertificateRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DeleteCertificateRequest" /> class.
        /// </summary>
        /// <param name="action">固定为 delete。 (required).</param>
        /// <param name="certKey">要删除的平台证书标识。 (required).</param>
        public DeleteCertificateRequest(ActionEnum action = default, string certKey = default)
        {
            this.Action = action;
            // to ensure "certKey" is required (not null)
            if (certKey == null)
            {
                throw new ArgumentNullException("certKey is a required property for DeleteCertificateRequest and cannot be null");
            }
            this.CertKey = certKey;
        }

        /// <summary>
        /// 要删除的平台证书标识。
        /// </summary>
        /// <value>要删除的平台证书标识。</value>
        [DataMember(Name = "certKey", IsRequired = true, EmitDefaultValue = true)]
        public string CertKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeleteCertificateRequest {\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  CertKey: ").Append(CertKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CertKey (string) minLength
            if (this.CertKey != null && this.CertKey.Length < 1)
            {
                yield return new ValidationResult("Invalid value for CertKey, length must be greater than 1.", new [] { "CertKey" });
            }

            yield break;
        }
    }

}
