/*
 * ANSSL OpenAPI
 *
 * ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Anssl.Client;
using Anssl.Model;

namespace Anssl.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICertificatesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 检查 DNS-01 CNAME 状态
        /// </summary>
        /// <remarks>
        /// 返回待验证域名需要配置的 CNAME 记录及当前解析状态。
        /// </remarks>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="checkDomainRequest"></param>
        /// <returns>CheckDomainSuccessResponse</returns>
        CheckDomainSuccessResponse CheckCertificateDomains(CheckDomainRequest checkDomainRequest);

        /// <summary>
        /// 检查 DNS-01 CNAME 状态
        /// </summary>
        /// <remarks>
        /// 返回待验证域名需要配置的 CNAME 记录及当前解析状态。
        /// </remarks>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="checkDomainRequest"></param>
        /// <returns>ApiResponse of CheckDomainSuccessResponse</returns>
        ApiResponse<CheckDomainSuccessResponse> CheckCertificateDomainsWithHttpInfo(CheckDomainRequest checkDomainRequest);
        /// <summary>
        /// 下载证书
        /// </summary>
        /// <remarks>
        /// format 默认为 tar；错误始终返回非 2xx JSON envelope。
        /// </remarks>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="certKey">证书对外唯一标识。</param>
        /// <param name="format">下载格式。 (optional, default to tar)</param>
        /// <returns>FileParameter</returns>
        FileParameter DownloadCertificate(string certKey, string? format = default);

        /// <summary>
        /// 下载证书
        /// </summary>
        /// <remarks>
        /// format 默认为 tar；错误始终返回非 2xx JSON envelope。
        /// </remarks>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="certKey">证书对外唯一标识。</param>
        /// <param name="format">下载格式。 (optional, default to tar)</param>
        /// <returns>ApiResponse of FileParameter</returns>
        ApiResponse<FileParameter> DownloadCertificateWithHttpInfo(string certKey, string? format = default);
        /// <summary>
        /// 查询证书详情
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="certKey">证书对外唯一标识。</param>
        /// <returns>CertificateDetailSuccessResponse</returns>
        CertificateDetailSuccessResponse GetCertificate(string certKey);

        /// <summary>
        /// 查询证书详情
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="certKey">证书对外唯一标识。</param>
        /// <returns>ApiResponse of CertificateDetailSuccessResponse</returns>
        ApiResponse<CertificateDetailSuccessResponse> GetCertificateWithHttpInfo(string certKey);
        /// <summary>
        /// 查询证书列表
        /// </summary>
        /// <remarks>
        /// 查询当前 AccessKey 所属用户的自动签发证书；未知 status 返回 400。
        /// </remarks>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">从 1 开始的页码。 (optional, default to 1)</param>
        /// <param name="size">每页数量，最大 100。 (optional, default to 20)</param>
        /// <param name="keyword">按证书主域名模糊搜索。 (optional)</param>
        /// <param name="status">按证书状态筛选。 (optional)</param>
        /// <returns>CertificateListSuccessResponse</returns>
        CertificateListSuccessResponse ListCertificates(int? page = default, int? size = default, string? keyword = default, CertificateStatus? status = default);

        /// <summary>
        /// 查询证书列表
        /// </summary>
        /// <remarks>
        /// 查询当前 AccessKey 所属用户的自动签发证书；未知 status 返回 400。
        /// </remarks>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">从 1 开始的页码。 (optional, default to 1)</param>
        /// <param name="size">每页数量，最大 100。 (optional, default to 20)</param>
        /// <param name="keyword">按证书主域名模糊搜索。 (optional)</param>
        /// <param name="status">按证书状态筛选。 (optional)</param>
        /// <returns>ApiResponse of CertificateListSuccessResponse</returns>
        ApiResponse<CertificateListSuccessResponse> ListCertificatesWithHttpInfo(int? page = default, int? size = default, string? keyword = default, CertificateStatus? status = default);
        /// <summary>
        /// 提交证书生命周期操作
        /// </summary>
        /// <remarks>
        /// 提交 apply、renew、revoke 或 delete。action 为空时默认为 apply。 apply、renew 和 revoke 返回字符串 operationId 和 requestKey；delete 同步完成。 
        /// </remarks>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submitCertificateActionRequest"></param>
        /// <returns>CertificateActionSuccessResponse</returns>
        CertificateActionSuccessResponse SubmitCertificateAction(SubmitCertificateActionRequest submitCertificateActionRequest);

        /// <summary>
        /// 提交证书生命周期操作
        /// </summary>
        /// <remarks>
        /// 提交 apply、renew、revoke 或 delete。action 为空时默认为 apply。 apply、renew 和 revoke 返回字符串 operationId 和 requestKey；delete 同步完成。 
        /// </remarks>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submitCertificateActionRequest"></param>
        /// <returns>ApiResponse of CertificateActionSuccessResponse</returns>
        ApiResponse<CertificateActionSuccessResponse> SubmitCertificateActionWithHttpInfo(SubmitCertificateActionRequest submitCertificateActionRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICertificatesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 检查 DNS-01 CNAME 状态
        /// </summary>
        /// <remarks>
        /// 返回待验证域名需要配置的 CNAME 记录及当前解析状态。
        /// </remarks>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="checkDomainRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CheckDomainSuccessResponse</returns>
        System.Threading.Tasks.Task<CheckDomainSuccessResponse> CheckCertificateDomainsAsync(CheckDomainRequest checkDomainRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 检查 DNS-01 CNAME 状态
        /// </summary>
        /// <remarks>
        /// 返回待验证域名需要配置的 CNAME 记录及当前解析状态。
        /// </remarks>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="checkDomainRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CheckDomainSuccessResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CheckDomainSuccessResponse>> CheckCertificateDomainsWithHttpInfoAsync(CheckDomainRequest checkDomainRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 下载证书
        /// </summary>
        /// <remarks>
        /// format 默认为 tar；错误始终返回非 2xx JSON envelope。
        /// </remarks>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="certKey">证书对外唯一标识。</param>
        /// <param name="format">下载格式。 (optional, default to tar)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of FileParameter</returns>
        System.Threading.Tasks.Task<FileParameter> DownloadCertificateAsync(string certKey, string? format = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 下载证书
        /// </summary>
        /// <remarks>
        /// format 默认为 tar；错误始终返回非 2xx JSON envelope。
        /// </remarks>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="certKey">证书对外唯一标识。</param>
        /// <param name="format">下载格式。 (optional, default to tar)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (FileParameter)</returns>
        System.Threading.Tasks.Task<ApiResponse<FileParameter>> DownloadCertificateWithHttpInfoAsync(string certKey, string? format = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 查询证书详情
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="certKey">证书对外唯一标识。</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CertificateDetailSuccessResponse</returns>
        System.Threading.Tasks.Task<CertificateDetailSuccessResponse> GetCertificateAsync(string certKey, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 查询证书详情
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="certKey">证书对外唯一标识。</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CertificateDetailSuccessResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CertificateDetailSuccessResponse>> GetCertificateWithHttpInfoAsync(string certKey, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 查询证书列表
        /// </summary>
        /// <remarks>
        /// 查询当前 AccessKey 所属用户的自动签发证书；未知 status 返回 400。
        /// </remarks>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">从 1 开始的页码。 (optional, default to 1)</param>
        /// <param name="size">每页数量，最大 100。 (optional, default to 20)</param>
        /// <param name="keyword">按证书主域名模糊搜索。 (optional)</param>
        /// <param name="status">按证书状态筛选。 (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CertificateListSuccessResponse</returns>
        System.Threading.Tasks.Task<CertificateListSuccessResponse> ListCertificatesAsync(int? page = default, int? size = default, string? keyword = default, CertificateStatus? status = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 查询证书列表
        /// </summary>
        /// <remarks>
        /// 查询当前 AccessKey 所属用户的自动签发证书；未知 status 返回 400。
        /// </remarks>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">从 1 开始的页码。 (optional, default to 1)</param>
        /// <param name="size">每页数量，最大 100。 (optional, default to 20)</param>
        /// <param name="keyword">按证书主域名模糊搜索。 (optional)</param>
        /// <param name="status">按证书状态筛选。 (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CertificateListSuccessResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CertificateListSuccessResponse>> ListCertificatesWithHttpInfoAsync(int? page = default, int? size = default, string? keyword = default, CertificateStatus? status = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 提交证书生命周期操作
        /// </summary>
        /// <remarks>
        /// 提交 apply、renew、revoke 或 delete。action 为空时默认为 apply。 apply、renew 和 revoke 返回字符串 operationId 和 requestKey；delete 同步完成。 
        /// </remarks>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submitCertificateActionRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CertificateActionSuccessResponse</returns>
        System.Threading.Tasks.Task<CertificateActionSuccessResponse> SubmitCertificateActionAsync(SubmitCertificateActionRequest submitCertificateActionRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 提交证书生命周期操作
        /// </summary>
        /// <remarks>
        /// 提交 apply、renew、revoke 或 delete。action 为空时默认为 apply。 apply、renew 和 revoke 返回字符串 operationId 和 requestKey；delete 同步完成。 
        /// </remarks>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submitCertificateActionRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CertificateActionSuccessResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CertificateActionSuccessResponse>> SubmitCertificateActionWithHttpInfoAsync(SubmitCertificateActionRequest submitCertificateActionRequest, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICertificatesApi : ICertificatesApiSync, ICertificatesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CertificatesApi : IDisposable, ICertificatesApi
    {
        private Anssl.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CertificatesApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public CertificatesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CertificatesApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public CertificatesApi(string basePath)
        {
            this.Configuration = Anssl.Client.Configuration.MergeConfigurations(
                Anssl.Client.GlobalConfiguration.Instance,
                new Anssl.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Anssl.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Anssl.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CertificatesApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public CertificatesApi(Anssl.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Anssl.Client.Configuration.MergeConfigurations(
                Anssl.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Anssl.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Anssl.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CertificatesApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public CertificatesApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CertificatesApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public CertificatesApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Anssl.Client.Configuration.MergeConfigurations(
                Anssl.Client.GlobalConfiguration.Instance,
                new Anssl.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Anssl.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Anssl.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CertificatesApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public CertificatesApi(HttpClient client, Anssl.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Anssl.Client.Configuration.MergeConfigurations(
                Anssl.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Anssl.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Anssl.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CertificatesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public CertificatesApi(Anssl.Client.ISynchronousClient client, Anssl.Client.IAsynchronousClient asyncClient, Anssl.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Anssl.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Anssl.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Anssl.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Anssl.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Anssl.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Anssl.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// 检查 DNS-01 CNAME 状态 返回待验证域名需要配置的 CNAME 记录及当前解析状态。
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="checkDomainRequest"></param>
        /// <returns>CheckDomainSuccessResponse</returns>
        public CheckDomainSuccessResponse CheckCertificateDomains(CheckDomainRequest checkDomainRequest)
        {
            Anssl.Client.ApiResponse<CheckDomainSuccessResponse> localVarResponse = CheckCertificateDomainsWithHttpInfo(checkDomainRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 检查 DNS-01 CNAME 状态 返回待验证域名需要配置的 CNAME 记录及当前解析状态。
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="checkDomainRequest"></param>
        /// <returns>ApiResponse of CheckDomainSuccessResponse</returns>
        public Anssl.Client.ApiResponse<CheckDomainSuccessResponse> CheckCertificateDomainsWithHttpInfo(CheckDomainRequest checkDomainRequest)
        {
            // verify the required parameter 'checkDomainRequest' is set
            if (checkDomainRequest == null)
                throw new Anssl.Client.ApiException(400, "Missing required parameter 'checkDomainRequest' when calling CertificatesApi->CheckCertificateDomains");

            Anssl.Client.RequestOptions localVarRequestOptions = new Anssl.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Anssl.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Anssl.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = checkDomainRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CheckDomainSuccessResponse>("/cert/check-domain", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CheckCertificateDomains", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 检查 DNS-01 CNAME 状态 返回待验证域名需要配置的 CNAME 记录及当前解析状态。
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="checkDomainRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CheckDomainSuccessResponse</returns>
        public async System.Threading.Tasks.Task<CheckDomainSuccessResponse> CheckCertificateDomainsAsync(CheckDomainRequest checkDomainRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            Anssl.Client.ApiResponse<CheckDomainSuccessResponse> localVarResponse = await CheckCertificateDomainsWithHttpInfoAsync(checkDomainRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 检查 DNS-01 CNAME 状态 返回待验证域名需要配置的 CNAME 记录及当前解析状态。
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="checkDomainRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CheckDomainSuccessResponse)</returns>
        public async System.Threading.Tasks.Task<Anssl.Client.ApiResponse<CheckDomainSuccessResponse>> CheckCertificateDomainsWithHttpInfoAsync(CheckDomainRequest checkDomainRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'checkDomainRequest' is set
            if (checkDomainRequest == null)
                throw new Anssl.Client.ApiException(400, "Missing required parameter 'checkDomainRequest' when calling CertificatesApi->CheckCertificateDomains");


            Anssl.Client.RequestOptions localVarRequestOptions = new Anssl.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Anssl.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Anssl.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = checkDomainRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<CheckDomainSuccessResponse>("/cert/check-domain", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CheckCertificateDomains", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 下载证书 format 默认为 tar；错误始终返回非 2xx JSON envelope。
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="certKey">证书对外唯一标识。</param>
        /// <param name="format">下载格式。 (optional, default to tar)</param>
        /// <returns>FileParameter</returns>
        public FileParameter DownloadCertificate(string certKey, string? format = default)
        {
            Anssl.Client.ApiResponse<FileParameter> localVarResponse = DownloadCertificateWithHttpInfo(certKey, format);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 下载证书 format 默认为 tar；错误始终返回非 2xx JSON envelope。
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="certKey">证书对外唯一标识。</param>
        /// <param name="format">下载格式。 (optional, default to tar)</param>
        /// <returns>ApiResponse of FileParameter</returns>
        public Anssl.Client.ApiResponse<FileParameter> DownloadCertificateWithHttpInfo(string certKey, string? format = default)
        {
            // verify the required parameter 'certKey' is set
            if (certKey == null)
                throw new Anssl.Client.ApiException(400, "Missing required parameter 'certKey' when calling CertificatesApi->DownloadCertificate");

            Anssl.Client.RequestOptions localVarRequestOptions = new Anssl.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/x-tar",
                "application/json"
            };

            var localVarContentType = Anssl.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Anssl.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("certKey", Anssl.Client.ClientUtils.ParameterToString(certKey)); // path parameter
            if (format != null)
            {
                localVarRequestOptions.QueryParameters.Add(Anssl.Client.ClientUtils.ParameterToMultiMap("", "format", format));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<FileParameter>("/cert/{certKey}/download", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DownloadCertificate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 下载证书 format 默认为 tar；错误始终返回非 2xx JSON envelope。
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="certKey">证书对外唯一标识。</param>
        /// <param name="format">下载格式。 (optional, default to tar)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of FileParameter</returns>
        public async System.Threading.Tasks.Task<FileParameter> DownloadCertificateAsync(string certKey, string? format = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Anssl.Client.ApiResponse<FileParameter> localVarResponse = await DownloadCertificateWithHttpInfoAsync(certKey, format, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 下载证书 format 默认为 tar；错误始终返回非 2xx JSON envelope。
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="certKey">证书对外唯一标识。</param>
        /// <param name="format">下载格式。 (optional, default to tar)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (FileParameter)</returns>
        public async System.Threading.Tasks.Task<Anssl.Client.ApiResponse<FileParameter>> DownloadCertificateWithHttpInfoAsync(string certKey, string? format = default, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'certKey' is set
            if (certKey == null)
                throw new Anssl.Client.ApiException(400, "Missing required parameter 'certKey' when calling CertificatesApi->DownloadCertificate");


            Anssl.Client.RequestOptions localVarRequestOptions = new Anssl.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/x-tar",
                "application/json"
            };


            var localVarContentType = Anssl.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Anssl.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("certKey", Anssl.Client.ClientUtils.ParameterToString(certKey)); // path parameter
            if (format != null)
            {
                localVarRequestOptions.QueryParameters.Add(Anssl.Client.ClientUtils.ParameterToMultiMap("", "format", format));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<FileParameter>("/cert/{certKey}/download", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DownloadCertificate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 查询证书详情 
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="certKey">证书对外唯一标识。</param>
        /// <returns>CertificateDetailSuccessResponse</returns>
        public CertificateDetailSuccessResponse GetCertificate(string certKey)
        {
            Anssl.Client.ApiResponse<CertificateDetailSuccessResponse> localVarResponse = GetCertificateWithHttpInfo(certKey);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 查询证书详情 
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="certKey">证书对外唯一标识。</param>
        /// <returns>ApiResponse of CertificateDetailSuccessResponse</returns>
        public Anssl.Client.ApiResponse<CertificateDetailSuccessResponse> GetCertificateWithHttpInfo(string certKey)
        {
            // verify the required parameter 'certKey' is set
            if (certKey == null)
                throw new Anssl.Client.ApiException(400, "Missing required parameter 'certKey' when calling CertificatesApi->GetCertificate");

            Anssl.Client.RequestOptions localVarRequestOptions = new Anssl.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Anssl.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Anssl.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("certKey", Anssl.Client.ClientUtils.ParameterToString(certKey)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<CertificateDetailSuccessResponse>("/cert/{certKey}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCertificate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 查询证书详情 
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="certKey">证书对外唯一标识。</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CertificateDetailSuccessResponse</returns>
        public async System.Threading.Tasks.Task<CertificateDetailSuccessResponse> GetCertificateAsync(string certKey, System.Threading.CancellationToken cancellationToken = default)
        {
            Anssl.Client.ApiResponse<CertificateDetailSuccessResponse> localVarResponse = await GetCertificateWithHttpInfoAsync(certKey, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 查询证书详情 
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="certKey">证书对外唯一标识。</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CertificateDetailSuccessResponse)</returns>
        public async System.Threading.Tasks.Task<Anssl.Client.ApiResponse<CertificateDetailSuccessResponse>> GetCertificateWithHttpInfoAsync(string certKey, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'certKey' is set
            if (certKey == null)
                throw new Anssl.Client.ApiException(400, "Missing required parameter 'certKey' when calling CertificatesApi->GetCertificate");


            Anssl.Client.RequestOptions localVarRequestOptions = new Anssl.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Anssl.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Anssl.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("certKey", Anssl.Client.ClientUtils.ParameterToString(certKey)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<CertificateDetailSuccessResponse>("/cert/{certKey}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCertificate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 查询证书列表 查询当前 AccessKey 所属用户的自动签发证书；未知 status 返回 400。
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">从 1 开始的页码。 (optional, default to 1)</param>
        /// <param name="size">每页数量，最大 100。 (optional, default to 20)</param>
        /// <param name="keyword">按证书主域名模糊搜索。 (optional)</param>
        /// <param name="status">按证书状态筛选。 (optional)</param>
        /// <returns>CertificateListSuccessResponse</returns>
        public CertificateListSuccessResponse ListCertificates(int? page = default, int? size = default, string? keyword = default, CertificateStatus? status = default)
        {
            Anssl.Client.ApiResponse<CertificateListSuccessResponse> localVarResponse = ListCertificatesWithHttpInfo(page, size, keyword, status);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 查询证书列表 查询当前 AccessKey 所属用户的自动签发证书；未知 status 返回 400。
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">从 1 开始的页码。 (optional, default to 1)</param>
        /// <param name="size">每页数量，最大 100。 (optional, default to 20)</param>
        /// <param name="keyword">按证书主域名模糊搜索。 (optional)</param>
        /// <param name="status">按证书状态筛选。 (optional)</param>
        /// <returns>ApiResponse of CertificateListSuccessResponse</returns>
        public Anssl.Client.ApiResponse<CertificateListSuccessResponse> ListCertificatesWithHttpInfo(int? page = default, int? size = default, string? keyword = default, CertificateStatus? status = default)
        {
            Anssl.Client.RequestOptions localVarRequestOptions = new Anssl.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Anssl.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Anssl.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Anssl.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (size != null)
            {
                localVarRequestOptions.QueryParameters.Add(Anssl.Client.ClientUtils.ParameterToMultiMap("", "size", size));
            }
            if (keyword != null)
            {
                localVarRequestOptions.QueryParameters.Add(Anssl.Client.ClientUtils.ParameterToMultiMap("", "keyword", keyword));
            }
            if (status != null)
            {
                localVarRequestOptions.QueryParameters.Add(Anssl.Client.ClientUtils.ParameterToMultiMap("", "status", status));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<CertificateListSuccessResponse>("/cert", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListCertificates", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 查询证书列表 查询当前 AccessKey 所属用户的自动签发证书；未知 status 返回 400。
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">从 1 开始的页码。 (optional, default to 1)</param>
        /// <param name="size">每页数量，最大 100。 (optional, default to 20)</param>
        /// <param name="keyword">按证书主域名模糊搜索。 (optional)</param>
        /// <param name="status">按证书状态筛选。 (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CertificateListSuccessResponse</returns>
        public async System.Threading.Tasks.Task<CertificateListSuccessResponse> ListCertificatesAsync(int? page = default, int? size = default, string? keyword = default, CertificateStatus? status = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Anssl.Client.ApiResponse<CertificateListSuccessResponse> localVarResponse = await ListCertificatesWithHttpInfoAsync(page, size, keyword, status, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 查询证书列表 查询当前 AccessKey 所属用户的自动签发证书；未知 status 返回 400。
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">从 1 开始的页码。 (optional, default to 1)</param>
        /// <param name="size">每页数量，最大 100。 (optional, default to 20)</param>
        /// <param name="keyword">按证书主域名模糊搜索。 (optional)</param>
        /// <param name="status">按证书状态筛选。 (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CertificateListSuccessResponse)</returns>
        public async System.Threading.Tasks.Task<Anssl.Client.ApiResponse<CertificateListSuccessResponse>> ListCertificatesWithHttpInfoAsync(int? page = default, int? size = default, string? keyword = default, CertificateStatus? status = default, System.Threading.CancellationToken cancellationToken = default)
        {

            Anssl.Client.RequestOptions localVarRequestOptions = new Anssl.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Anssl.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Anssl.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Anssl.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (size != null)
            {
                localVarRequestOptions.QueryParameters.Add(Anssl.Client.ClientUtils.ParameterToMultiMap("", "size", size));
            }
            if (keyword != null)
            {
                localVarRequestOptions.QueryParameters.Add(Anssl.Client.ClientUtils.ParameterToMultiMap("", "keyword", keyword));
            }
            if (status != null)
            {
                localVarRequestOptions.QueryParameters.Add(Anssl.Client.ClientUtils.ParameterToMultiMap("", "status", status));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<CertificateListSuccessResponse>("/cert", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListCertificates", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 提交证书生命周期操作 提交 apply、renew、revoke 或 delete。action 为空时默认为 apply。 apply、renew 和 revoke 返回字符串 operationId 和 requestKey；delete 同步完成。 
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submitCertificateActionRequest"></param>
        /// <returns>CertificateActionSuccessResponse</returns>
        public CertificateActionSuccessResponse SubmitCertificateAction(SubmitCertificateActionRequest submitCertificateActionRequest)
        {
            Anssl.Client.ApiResponse<CertificateActionSuccessResponse> localVarResponse = SubmitCertificateActionWithHttpInfo(submitCertificateActionRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 提交证书生命周期操作 提交 apply、renew、revoke 或 delete。action 为空时默认为 apply。 apply、renew 和 revoke 返回字符串 operationId 和 requestKey；delete 同步完成。 
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submitCertificateActionRequest"></param>
        /// <returns>ApiResponse of CertificateActionSuccessResponse</returns>
        public Anssl.Client.ApiResponse<CertificateActionSuccessResponse> SubmitCertificateActionWithHttpInfo(SubmitCertificateActionRequest submitCertificateActionRequest)
        {
            // verify the required parameter 'submitCertificateActionRequest' is set
            if (submitCertificateActionRequest == null)
                throw new Anssl.Client.ApiException(400, "Missing required parameter 'submitCertificateActionRequest' when calling CertificatesApi->SubmitCertificateAction");

            Anssl.Client.RequestOptions localVarRequestOptions = new Anssl.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Anssl.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Anssl.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = submitCertificateActionRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CertificateActionSuccessResponse>("/cert/apply", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SubmitCertificateAction", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 提交证书生命周期操作 提交 apply、renew、revoke 或 delete。action 为空时默认为 apply。 apply、renew 和 revoke 返回字符串 operationId 和 requestKey；delete 同步完成。 
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submitCertificateActionRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CertificateActionSuccessResponse</returns>
        public async System.Threading.Tasks.Task<CertificateActionSuccessResponse> SubmitCertificateActionAsync(SubmitCertificateActionRequest submitCertificateActionRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            Anssl.Client.ApiResponse<CertificateActionSuccessResponse> localVarResponse = await SubmitCertificateActionWithHttpInfoAsync(submitCertificateActionRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 提交证书生命周期操作 提交 apply、renew、revoke 或 delete。action 为空时默认为 apply。 apply、renew 和 revoke 返回字符串 operationId 和 requestKey；delete 同步完成。 
        /// </summary>
        /// <exception cref="Anssl.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submitCertificateActionRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CertificateActionSuccessResponse)</returns>
        public async System.Threading.Tasks.Task<Anssl.Client.ApiResponse<CertificateActionSuccessResponse>> SubmitCertificateActionWithHttpInfoAsync(SubmitCertificateActionRequest submitCertificateActionRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'submitCertificateActionRequest' is set
            if (submitCertificateActionRequest == null)
                throw new Anssl.Client.ApiException(400, "Missing required parameter 'submitCertificateActionRequest' when calling CertificatesApi->SubmitCertificateAction");


            Anssl.Client.RequestOptions localVarRequestOptions = new Anssl.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Anssl.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Anssl.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = submitCertificateActionRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<CertificateActionSuccessResponse>("/cert/apply", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SubmitCertificateAction", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
