<?php
/**
 * CertificateDetail
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Anssl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ANSSL OpenAPI
 *
 * ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Anssl\Model;

use \ArrayAccess;
use \Anssl\ObjectSerializer;

/**
 * CertificateDetail Class Doc Comment
 *
 * @category Class
 * @package  Anssl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CertificateDetail implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'CertificateDetail';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'certKey' => 'string',
        'status' => '\Anssl\Model\CertificateStatus',
        'domains' => 'string[]',
        'ca' => '\Anssl\Model\CertificateAuthority',
        'keyAlgorithm' => '\Anssl\Model\CertificateKeyAlgorithm',
        'notBefore' => '\DateTime',
        'notAfter' => '\DateTime',
        'daysLeft' => 'int',
        'failureReason' => 'string',
        'createdAt' => '\DateTime',
        'updatedAt' => '\DateTime'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'certKey' => null,
        'status' => null,
        'domains' => null,
        'ca' => null,
        'keyAlgorithm' => null,
        'notBefore' => 'date-time',
        'notAfter' => 'date-time',
        'daysLeft' => 'int32',
        'failureReason' => null,
        'createdAt' => 'date-time',
        'updatedAt' => 'date-time'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'certKey' => false,
        'status' => false,
        'domains' => false,
        'ca' => false,
        'keyAlgorithm' => false,
        'notBefore' => false,
        'notAfter' => false,
        'daysLeft' => false,
        'failureReason' => false,
        'createdAt' => false,
        'updatedAt' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'certKey' => 'certKey',
        'status' => 'status',
        'domains' => 'domains',
        'ca' => 'ca',
        'keyAlgorithm' => 'keyAlgorithm',
        'notBefore' => 'notBefore',
        'notAfter' => 'notAfter',
        'daysLeft' => 'daysLeft',
        'failureReason' => 'failureReason',
        'createdAt' => 'createdAt',
        'updatedAt' => 'updatedAt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'certKey' => 'setCertKey',
        'status' => 'setStatus',
        'domains' => 'setDomains',
        'ca' => 'setCa',
        'keyAlgorithm' => 'setKeyAlgorithm',
        'notBefore' => 'setNotBefore',
        'notAfter' => 'setNotAfter',
        'daysLeft' => 'setDaysLeft',
        'failureReason' => 'setFailureReason',
        'createdAt' => 'setCreatedAt',
        'updatedAt' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'certKey' => 'getCertKey',
        'status' => 'getStatus',
        'domains' => 'getDomains',
        'ca' => 'getCa',
        'keyAlgorithm' => 'getKeyAlgorithm',
        'notBefore' => 'getNotBefore',
        'notAfter' => 'getNotAfter',
        'daysLeft' => 'getDaysLeft',
        'failureReason' => 'getFailureReason',
        'createdAt' => 'getCreatedAt',
        'updatedAt' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('certKey', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('domains', $data ?? [], null);
        $this->setIfExists('ca', $data ?? [], null);
        $this->setIfExists('keyAlgorithm', $data ?? [], null);
        $this->setIfExists('notBefore', $data ?? [], null);
        $this->setIfExists('notAfter', $data ?? [], null);
        $this->setIfExists('daysLeft', $data ?? [], null);
        $this->setIfExists('failureReason', $data ?? [], null);
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('updatedAt', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['certKey'] === null) {
            $invalidProperties[] = "'certKey' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['domains'] === null) {
            $invalidProperties[] = "'domains' can't be null";
        }
        if ($this->container['ca'] === null) {
            $invalidProperties[] = "'ca' can't be null";
        }
        if ($this->container['keyAlgorithm'] === null) {
            $invalidProperties[] = "'keyAlgorithm' can't be null";
        }
        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        if ($this->container['updatedAt'] === null) {
            $invalidProperties[] = "'updatedAt' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets certKey
     *
     * @return string
     */
    public function getCertKey()
    {
        return $this->container['certKey'];
    }

    /**
     * Sets certKey
     *
     * @param string $certKey 证书外部唯一标识。
     *
     * @return self
     */
    public function setCertKey($certKey)
    {
        if (is_null($certKey)) {
            throw new \InvalidArgumentException('non-nullable certKey cannot be null');
        }
        $this->container['certKey'] = $certKey;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Anssl\Model\CertificateStatus
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Anssl\Model\CertificateStatus $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets domains
     *
     * @return string[]
     */
    public function getDomains()
    {
        return $this->container['domains'];
    }

    /**
     * Sets domains
     *
     * @param string[] $domains 证书域名列表。
     *
     * @return self
     */
    public function setDomains($domains)
    {
        if (is_null($domains)) {
            throw new \InvalidArgumentException('non-nullable domains cannot be null');
        }
        $this->container['domains'] = $domains;

        return $this;
    }

    /**
     * Gets ca
     *
     * @return \Anssl\Model\CertificateAuthority
     */
    public function getCa()
    {
        return $this->container['ca'];
    }

    /**
     * Sets ca
     *
     * @param \Anssl\Model\CertificateAuthority $ca ca
     *
     * @return self
     */
    public function setCa($ca)
    {
        if (is_null($ca)) {
            throw new \InvalidArgumentException('non-nullable ca cannot be null');
        }
        $this->container['ca'] = $ca;

        return $this;
    }

    /**
     * Gets keyAlgorithm
     *
     * @return \Anssl\Model\CertificateKeyAlgorithm
     */
    public function getKeyAlgorithm()
    {
        return $this->container['keyAlgorithm'];
    }

    /**
     * Sets keyAlgorithm
     *
     * @param \Anssl\Model\CertificateKeyAlgorithm $keyAlgorithm keyAlgorithm
     *
     * @return self
     */
    public function setKeyAlgorithm($keyAlgorithm)
    {
        if (is_null($keyAlgorithm)) {
            throw new \InvalidArgumentException('non-nullable keyAlgorithm cannot be null');
        }
        $this->container['keyAlgorithm'] = $keyAlgorithm;

        return $this;
    }

    /**
     * Gets notBefore
     *
     * @return \DateTime|null
     */
    public function getNotBefore()
    {
        return $this->container['notBefore'];
    }

    /**
     * Sets notBefore
     *
     * @param \DateTime|null $notBefore 证书生效时间。
     *
     * @return self
     */
    public function setNotBefore($notBefore)
    {
        if (is_null($notBefore)) {
            throw new \InvalidArgumentException('non-nullable notBefore cannot be null');
        }
        $this->container['notBefore'] = $notBefore;

        return $this;
    }

    /**
     * Gets notAfter
     *
     * @return \DateTime|null
     */
    public function getNotAfter()
    {
        return $this->container['notAfter'];
    }

    /**
     * Sets notAfter
     *
     * @param \DateTime|null $notAfter 证书过期时间。
     *
     * @return self
     */
    public function setNotAfter($notAfter)
    {
        if (is_null($notAfter)) {
            throw new \InvalidArgumentException('non-nullable notAfter cannot be null');
        }
        $this->container['notAfter'] = $notAfter;

        return $this;
    }

    /**
     * Gets daysLeft
     *
     * @return int|null
     */
    public function getDaysLeft()
    {
        return $this->container['daysLeft'];
    }

    /**
     * Sets daysLeft
     *
     * @param int|null $daysLeft 剩余有效天数。
     *
     * @return self
     */
    public function setDaysLeft($daysLeft)
    {
        if (is_null($daysLeft)) {
            throw new \InvalidArgumentException('non-nullable daysLeft cannot be null');
        }
        $this->container['daysLeft'] = $daysLeft;

        return $this;
    }

    /**
     * Gets failureReason
     *
     * @return string|null
     */
    public function getFailureReason()
    {
        return $this->container['failureReason'];
    }

    /**
     * Sets failureReason
     *
     * @param string|null $failureReason 最近失败原因。
     *
     * @return self
     */
    public function setFailureReason($failureReason)
    {
        if (is_null($failureReason)) {
            throw new \InvalidArgumentException('non-nullable failureReason cannot be null');
        }
        $this->container['failureReason'] = $failureReason;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param \DateTime $createdAt 记录创建时间。
     *
     * @return self
     */
    public function setCreatedAt($createdAt)
    {
        if (is_null($createdAt)) {
            throw new \InvalidArgumentException('non-nullable createdAt cannot be null');
        }
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updatedAt'];
    }

    /**
     * Sets updatedAt
     *
     * @param \DateTime $updatedAt 记录更新时间。
     *
     * @return self
     */
    public function setUpdatedAt($updatedAt)
    {
        if (is_null($updatedAt)) {
            throw new \InvalidArgumentException('non-nullable updatedAt cannot be null');
        }
        $this->container['updatedAt'] = $updatedAt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


