<?php
/**
 * CertificateOperationStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Anssl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ANSSL OpenAPI
 *
 * ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Anssl\Model;
use \Anssl\ObjectSerializer;

/**
 * CertificateOperationStatus Class Doc Comment
 *
 * @category Class
 * @description 异步操作执行状态。
 * @package  Anssl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CertificateOperationStatus
{
    /**
     * Possible values of this enum
     */
    public const PENDING = 'pending';

    public const RUNNING = 'running';

    public const WAITING_VALIDATION = 'waiting_validation';

    public const SUCCEEDED = 'succeeded';

    public const FAILED = 'failed';

    public const CANCELED = 'canceled';

    public const UNKNOWN = 'unknown';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PENDING,
            self::RUNNING,
            self::WAITING_VALIDATION,
            self::SUCCEEDED,
            self::FAILED,
            self::CANCELED,
            self::UNKNOWN
        ];
    }
}


