<?php
/**
 * CertificateActionStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Anssl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ANSSL OpenAPI
 *
 * ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Anssl\Model;
use \Anssl\ObjectSerializer;

/**
 * CertificateActionStatus Class Doc Comment
 *
 * @category Class
 * @description 生命周期请求受理后的提示状态。
 * @package  Anssl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CertificateActionStatus
{
    /**
     * Possible values of this enum
     */
    public const APPLYING = 'applying';

    public const RENEWING = 'renewing';

    public const REVOKING = 'revoking';

    public const DELETED = 'deleted';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::APPLYING,
            self::RENEWING,
            self::REVOKING,
            self::DELETED
        ];
    }
}


