<?php
/**
 * CertificatesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Anssl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ANSSL OpenAPI
 *
 * ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Anssl\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Anssl\ApiException;
use Anssl\Configuration;
use Anssl\FormDataProcessor;
use Anssl\HeaderSelector;
use Anssl\ObjectSerializer;

/**
 * CertificatesApi Class Doc Comment
 *
 * @category Class
 * @package  Anssl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CertificatesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'checkCertificateDomains' => [
            'application/json',
        ],
        'downloadCertificate' => [
            'application/json',
        ],
        'getCertificate' => [
            'application/json',
        ],
        'listCertificates' => [
            'application/json',
        ],
        'submitCertificateAction' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation checkCertificateDomains
     *
     * 检查 DNS-01 CNAME 状态
     *
     * @param  \Anssl\Model\CheckDomainRequest $checkDomainRequest checkDomainRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkCertificateDomains'] to see the possible values for this operation
     *
     * @throws \Anssl\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Anssl\Model\CheckDomainSuccessResponse|\Anssl\Model\Error400|\Anssl\Model\Error401|\Anssl\Model\Error404|\Anssl\Model\Error429|\Anssl\Model\Error500
     */
    public function checkCertificateDomains($checkDomainRequest, string $contentType = self::contentTypes['checkCertificateDomains'][0])
    {
        list($response) = $this->checkCertificateDomainsWithHttpInfo($checkDomainRequest, $contentType);
        return $response;
    }

    /**
     * Operation checkCertificateDomainsWithHttpInfo
     *
     * 检查 DNS-01 CNAME 状态
     *
     * @param  \Anssl\Model\CheckDomainRequest $checkDomainRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkCertificateDomains'] to see the possible values for this operation
     *
     * @throws \Anssl\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Anssl\Model\CheckDomainSuccessResponse|\Anssl\Model\Error400|\Anssl\Model\Error401|\Anssl\Model\Error404|\Anssl\Model\Error429|\Anssl\Model\Error500, HTTP status code, HTTP response headers (array of strings)
     */
    public function checkCertificateDomainsWithHttpInfo($checkDomainRequest, string $contentType = self::contentTypes['checkCertificateDomains'][0])
    {
        $request = $this->checkCertificateDomainsRequest($checkDomainRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\CheckDomainSuccessResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error400',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error401',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error404',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error429',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error500',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Anssl\Model\CheckDomainSuccessResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\CheckDomainSuccessResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error401',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error404',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error429',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error500',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation checkCertificateDomainsAsync
     *
     * 检查 DNS-01 CNAME 状态
     *
     * @param  \Anssl\Model\CheckDomainRequest $checkDomainRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkCertificateDomains'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function checkCertificateDomainsAsync($checkDomainRequest, string $contentType = self::contentTypes['checkCertificateDomains'][0])
    {
        return $this->checkCertificateDomainsAsyncWithHttpInfo($checkDomainRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation checkCertificateDomainsAsyncWithHttpInfo
     *
     * 检查 DNS-01 CNAME 状态
     *
     * @param  \Anssl\Model\CheckDomainRequest $checkDomainRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkCertificateDomains'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function checkCertificateDomainsAsyncWithHttpInfo($checkDomainRequest, string $contentType = self::contentTypes['checkCertificateDomains'][0])
    {
        $returnType = '\Anssl\Model\CheckDomainSuccessResponse';
        $request = $this->checkCertificateDomainsRequest($checkDomainRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'checkCertificateDomains'
     *
     * @param  \Anssl\Model\CheckDomainRequest $checkDomainRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkCertificateDomains'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function checkCertificateDomainsRequest($checkDomainRequest, string $contentType = self::contentTypes['checkCertificateDomains'][0])
    {

        // verify the required parameter 'checkDomainRequest' is set
        if ($checkDomainRequest === null || (is_array($checkDomainRequest) && count($checkDomainRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $checkDomainRequest when calling checkCertificateDomains'
            );
        }


        $resourcePath = '/cert/check-domain';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($checkDomainRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($checkDomainRequest));
            } else {
                $httpBody = $checkDomainRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation downloadCertificate
     *
     * 下载证书
     *
     * @param  string $certKey 证书对外唯一标识。 (required)
     * @param  string|null $format 下载格式。 (optional, default to 'tar')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['downloadCertificate'] to see the possible values for this operation
     *
     * @throws \Anssl\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \SplFileObject|\Anssl\Model\Error400|\Anssl\Model\Error401|\Anssl\Model\Error404|\Anssl\Model\Error409|\Anssl\Model\Error429|\Anssl\Model\Error500
     */
    public function downloadCertificate($certKey, $format = 'tar', string $contentType = self::contentTypes['downloadCertificate'][0])
    {
        list($response) = $this->downloadCertificateWithHttpInfo($certKey, $format, $contentType);
        return $response;
    }

    /**
     * Operation downloadCertificateWithHttpInfo
     *
     * 下载证书
     *
     * @param  string $certKey 证书对外唯一标识。 (required)
     * @param  string|null $format 下载格式。 (optional, default to 'tar')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['downloadCertificate'] to see the possible values for this operation
     *
     * @throws \Anssl\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \SplFileObject|\Anssl\Model\Error400|\Anssl\Model\Error401|\Anssl\Model\Error404|\Anssl\Model\Error409|\Anssl\Model\Error429|\Anssl\Model\Error500, HTTP status code, HTTP response headers (array of strings)
     */
    public function downloadCertificateWithHttpInfo($certKey, $format = 'tar', string $contentType = self::contentTypes['downloadCertificate'][0])
    {
        $request = $this->downloadCertificateRequest($certKey, $format, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\SplFileObject',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error400',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error401',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error404',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error409',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error429',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error500',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\SplFileObject',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SplFileObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error401',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error404',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error409',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error429',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error500',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation downloadCertificateAsync
     *
     * 下载证书
     *
     * @param  string $certKey 证书对外唯一标识。 (required)
     * @param  string|null $format 下载格式。 (optional, default to 'tar')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['downloadCertificate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function downloadCertificateAsync($certKey, $format = 'tar', string $contentType = self::contentTypes['downloadCertificate'][0])
    {
        return $this->downloadCertificateAsyncWithHttpInfo($certKey, $format, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation downloadCertificateAsyncWithHttpInfo
     *
     * 下载证书
     *
     * @param  string $certKey 证书对外唯一标识。 (required)
     * @param  string|null $format 下载格式。 (optional, default to 'tar')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['downloadCertificate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function downloadCertificateAsyncWithHttpInfo($certKey, $format = 'tar', string $contentType = self::contentTypes['downloadCertificate'][0])
    {
        $returnType = '\SplFileObject';
        $request = $this->downloadCertificateRequest($certKey, $format, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'downloadCertificate'
     *
     * @param  string $certKey 证书对外唯一标识。 (required)
     * @param  string|null $format 下载格式。 (optional, default to 'tar')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['downloadCertificate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function downloadCertificateRequest($certKey, $format = 'tar', string $contentType = self::contentTypes['downloadCertificate'][0])
    {

        // verify the required parameter 'certKey' is set
        if ($certKey === null || (is_array($certKey) && count($certKey) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $certKey when calling downloadCertificate'
            );
        }
        if (strlen($certKey) < 1) {
            throw new \InvalidArgumentException('invalid length for "$certKey" when calling CertificatesApi.downloadCertificate, must be bigger than or equal to 1.');
        }
        


        $resourcePath = '/cert/{certKey}/download';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $format,
            'format', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($certKey !== null) {
            $resourcePath = str_replace(
                '{certKey}',
                ObjectSerializer::toPathValue($certKey),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/x-tar', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCertificate
     *
     * 查询证书详情
     *
     * @param  string $certKey 证书对外唯一标识。 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCertificate'] to see the possible values for this operation
     *
     * @throws \Anssl\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Anssl\Model\CertificateDetailSuccessResponse|\Anssl\Model\Error400|\Anssl\Model\Error401|\Anssl\Model\Error404|\Anssl\Model\Error429|\Anssl\Model\Error500
     */
    public function getCertificate($certKey, string $contentType = self::contentTypes['getCertificate'][0])
    {
        list($response) = $this->getCertificateWithHttpInfo($certKey, $contentType);
        return $response;
    }

    /**
     * Operation getCertificateWithHttpInfo
     *
     * 查询证书详情
     *
     * @param  string $certKey 证书对外唯一标识。 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCertificate'] to see the possible values for this operation
     *
     * @throws \Anssl\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Anssl\Model\CertificateDetailSuccessResponse|\Anssl\Model\Error400|\Anssl\Model\Error401|\Anssl\Model\Error404|\Anssl\Model\Error429|\Anssl\Model\Error500, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCertificateWithHttpInfo($certKey, string $contentType = self::contentTypes['getCertificate'][0])
    {
        $request = $this->getCertificateRequest($certKey, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\CertificateDetailSuccessResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error400',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error401',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error404',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error429',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error500',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Anssl\Model\CertificateDetailSuccessResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\CertificateDetailSuccessResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error401',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error404',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error429',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error500',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getCertificateAsync
     *
     * 查询证书详情
     *
     * @param  string $certKey 证书对外唯一标识。 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCertificate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCertificateAsync($certKey, string $contentType = self::contentTypes['getCertificate'][0])
    {
        return $this->getCertificateAsyncWithHttpInfo($certKey, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCertificateAsyncWithHttpInfo
     *
     * 查询证书详情
     *
     * @param  string $certKey 证书对外唯一标识。 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCertificate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCertificateAsyncWithHttpInfo($certKey, string $contentType = self::contentTypes['getCertificate'][0])
    {
        $returnType = '\Anssl\Model\CertificateDetailSuccessResponse';
        $request = $this->getCertificateRequest($certKey, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCertificate'
     *
     * @param  string $certKey 证书对外唯一标识。 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCertificate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCertificateRequest($certKey, string $contentType = self::contentTypes['getCertificate'][0])
    {

        // verify the required parameter 'certKey' is set
        if ($certKey === null || (is_array($certKey) && count($certKey) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $certKey when calling getCertificate'
            );
        }
        if (strlen($certKey) < 1) {
            throw new \InvalidArgumentException('invalid length for "$certKey" when calling CertificatesApi.getCertificate, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/cert/{certKey}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($certKey !== null) {
            $resourcePath = str_replace(
                '{certKey}',
                ObjectSerializer::toPathValue($certKey),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listCertificates
     *
     * 查询证书列表
     *
     * @param  int|null $page 从 1 开始的页码。 (optional, default to 1)
     * @param  int|null $size 每页数量，最大 100。 (optional, default to 20)
     * @param  string|null $keyword 按证书主域名模糊搜索。 (optional)
     * @param  \Anssl\Model\CertificateStatus|null $status 按证书状态筛选。 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCertificates'] to see the possible values for this operation
     *
     * @throws \Anssl\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Anssl\Model\CertificateListSuccessResponse|\Anssl\Model\Error400|\Anssl\Model\Error401|\Anssl\Model\Error429|\Anssl\Model\Error500
     */
    public function listCertificates($page = 1, $size = 20, $keyword = null, $status = null, string $contentType = self::contentTypes['listCertificates'][0])
    {
        list($response) = $this->listCertificatesWithHttpInfo($page, $size, $keyword, $status, $contentType);
        return $response;
    }

    /**
     * Operation listCertificatesWithHttpInfo
     *
     * 查询证书列表
     *
     * @param  int|null $page 从 1 开始的页码。 (optional, default to 1)
     * @param  int|null $size 每页数量，最大 100。 (optional, default to 20)
     * @param  string|null $keyword 按证书主域名模糊搜索。 (optional)
     * @param  \Anssl\Model\CertificateStatus|null $status 按证书状态筛选。 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCertificates'] to see the possible values for this operation
     *
     * @throws \Anssl\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Anssl\Model\CertificateListSuccessResponse|\Anssl\Model\Error400|\Anssl\Model\Error401|\Anssl\Model\Error429|\Anssl\Model\Error500, HTTP status code, HTTP response headers (array of strings)
     */
    public function listCertificatesWithHttpInfo($page = 1, $size = 20, $keyword = null, $status = null, string $contentType = self::contentTypes['listCertificates'][0])
    {
        $request = $this->listCertificatesRequest($page, $size, $keyword, $status, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\CertificateListSuccessResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error400',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error401',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error429',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error500',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Anssl\Model\CertificateListSuccessResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\CertificateListSuccessResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error401',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error429',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error500',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listCertificatesAsync
     *
     * 查询证书列表
     *
     * @param  int|null $page 从 1 开始的页码。 (optional, default to 1)
     * @param  int|null $size 每页数量，最大 100。 (optional, default to 20)
     * @param  string|null $keyword 按证书主域名模糊搜索。 (optional)
     * @param  \Anssl\Model\CertificateStatus|null $status 按证书状态筛选。 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCertificates'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listCertificatesAsync($page = 1, $size = 20, $keyword = null, $status = null, string $contentType = self::contentTypes['listCertificates'][0])
    {
        return $this->listCertificatesAsyncWithHttpInfo($page, $size, $keyword, $status, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listCertificatesAsyncWithHttpInfo
     *
     * 查询证书列表
     *
     * @param  int|null $page 从 1 开始的页码。 (optional, default to 1)
     * @param  int|null $size 每页数量，最大 100。 (optional, default to 20)
     * @param  string|null $keyword 按证书主域名模糊搜索。 (optional)
     * @param  \Anssl\Model\CertificateStatus|null $status 按证书状态筛选。 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCertificates'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listCertificatesAsyncWithHttpInfo($page = 1, $size = 20, $keyword = null, $status = null, string $contentType = self::contentTypes['listCertificates'][0])
    {
        $returnType = '\Anssl\Model\CertificateListSuccessResponse';
        $request = $this->listCertificatesRequest($page, $size, $keyword, $status, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listCertificates'
     *
     * @param  int|null $page 从 1 开始的页码。 (optional, default to 1)
     * @param  int|null $size 每页数量，最大 100。 (optional, default to 20)
     * @param  string|null $keyword 按证书主域名模糊搜索。 (optional)
     * @param  \Anssl\Model\CertificateStatus|null $status 按证书状态筛选。 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCertificates'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listCertificatesRequest($page = 1, $size = 20, $keyword = null, $status = null, string $contentType = self::contentTypes['listCertificates'][0])
    {

        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling CertificatesApi.listCertificates, must be bigger than or equal to 1.');
        }
        
        if ($size !== null && $size > 100) {
            throw new \InvalidArgumentException('invalid value for "$size" when calling CertificatesApi.listCertificates, must be smaller than or equal to 100.');
        }
        if ($size !== null && $size < 1) {
            throw new \InvalidArgumentException('invalid value for "$size" when calling CertificatesApi.listCertificates, must be bigger than or equal to 1.');
        }
        



        $resourcePath = '/cert';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $size,
            'size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $keyword,
            'keyword', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $status,
            'status', // param base name
            'CertificateStatus', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation submitCertificateAction
     *
     * 提交证书生命周期操作
     *
     * @param  \Anssl\Model\SubmitCertificateActionRequest $submitCertificateActionRequest submitCertificateActionRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['submitCertificateAction'] to see the possible values for this operation
     *
     * @throws \Anssl\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Anssl\Model\CertificateActionSuccessResponse|\Anssl\Model\Error400|\Anssl\Model\Error401|\Anssl\Model\Error404|\Anssl\Model\Error409|\Anssl\Model\Error429|\Anssl\Model\Error500
     */
    public function submitCertificateAction($submitCertificateActionRequest, string $contentType = self::contentTypes['submitCertificateAction'][0])
    {
        list($response) = $this->submitCertificateActionWithHttpInfo($submitCertificateActionRequest, $contentType);
        return $response;
    }

    /**
     * Operation submitCertificateActionWithHttpInfo
     *
     * 提交证书生命周期操作
     *
     * @param  \Anssl\Model\SubmitCertificateActionRequest $submitCertificateActionRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['submitCertificateAction'] to see the possible values for this operation
     *
     * @throws \Anssl\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Anssl\Model\CertificateActionSuccessResponse|\Anssl\Model\Error400|\Anssl\Model\Error401|\Anssl\Model\Error404|\Anssl\Model\Error409|\Anssl\Model\Error429|\Anssl\Model\Error500, HTTP status code, HTTP response headers (array of strings)
     */
    public function submitCertificateActionWithHttpInfo($submitCertificateActionRequest, string $contentType = self::contentTypes['submitCertificateAction'][0])
    {
        $request = $this->submitCertificateActionRequest($submitCertificateActionRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\CertificateActionSuccessResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error400',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error401',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error404',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error409',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error429',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Anssl\Model\Error500',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Anssl\Model\CertificateActionSuccessResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\CertificateActionSuccessResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error401',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error404',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error409',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error429',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Anssl\Model\Error500',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation submitCertificateActionAsync
     *
     * 提交证书生命周期操作
     *
     * @param  \Anssl\Model\SubmitCertificateActionRequest $submitCertificateActionRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['submitCertificateAction'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function submitCertificateActionAsync($submitCertificateActionRequest, string $contentType = self::contentTypes['submitCertificateAction'][0])
    {
        return $this->submitCertificateActionAsyncWithHttpInfo($submitCertificateActionRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation submitCertificateActionAsyncWithHttpInfo
     *
     * 提交证书生命周期操作
     *
     * @param  \Anssl\Model\SubmitCertificateActionRequest $submitCertificateActionRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['submitCertificateAction'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function submitCertificateActionAsyncWithHttpInfo($submitCertificateActionRequest, string $contentType = self::contentTypes['submitCertificateAction'][0])
    {
        $returnType = '\Anssl\Model\CertificateActionSuccessResponse';
        $request = $this->submitCertificateActionRequest($submitCertificateActionRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'submitCertificateAction'
     *
     * @param  \Anssl\Model\SubmitCertificateActionRequest $submitCertificateActionRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['submitCertificateAction'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function submitCertificateActionRequest($submitCertificateActionRequest, string $contentType = self::contentTypes['submitCertificateAction'][0])
    {

        // verify the required parameter 'submitCertificateActionRequest' is set
        if ($submitCertificateActionRequest === null || (is_array($submitCertificateActionRequest) && count($submitCertificateActionRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $submitCertificateActionRequest when calling submitCertificateAction'
            );
        }


        $resourcePath = '/cert/apply';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($submitCertificateActionRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($submitCertificateActionRequest));
            } else {
                $httpBody = $submitCertificateActionRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
