/*
 * ANSSL OpenAPI
 * ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cn.anssl.sdk.api;

import cn.anssl.sdk.ApiClient;
import cn.anssl.sdk.ApiException;
import cn.anssl.sdk.ApiResponse;
import cn.anssl.sdk.Configuration;
import cn.anssl.sdk.Pair;

import cn.anssl.sdk.model.CertificateActionSuccessResponse;
import cn.anssl.sdk.model.CertificateDetailSuccessResponse;
import cn.anssl.sdk.model.CertificateDownloadSuccessResponse;
import cn.anssl.sdk.model.CertificateListSuccessResponse;
import cn.anssl.sdk.model.CertificateStatus;
import cn.anssl.sdk.model.CheckDomainRequest;
import cn.anssl.sdk.model.CheckDomainSuccessResponse;
import cn.anssl.sdk.model.Error400;
import cn.anssl.sdk.model.Error401;
import cn.anssl.sdk.model.Error404;
import cn.anssl.sdk.model.Error409;
import cn.anssl.sdk.model.Error429;
import cn.anssl.sdk.model.Error500;
import java.io.File;
import cn.anssl.sdk.model.SubmitCertificateActionRequest;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class CertificatesApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public CertificatesApi() {
    this(Configuration.getDefaultApiClient());
  }

  public CertificatesApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * 检查 DNS-01 CNAME 状态
   * 返回待验证域名需要配置的 CNAME 记录及当前解析状态。
   * @param checkDomainRequest  (required)
   * @return CheckDomainSuccessResponse
   * @throws ApiException if fails to make API call
   */
  public CheckDomainSuccessResponse checkCertificateDomains(@javax.annotation.Nonnull CheckDomainRequest checkDomainRequest) throws ApiException {
    return checkCertificateDomains(checkDomainRequest, null);
  }

  /**
   * 检查 DNS-01 CNAME 状态
   * 返回待验证域名需要配置的 CNAME 记录及当前解析状态。
   * @param checkDomainRequest  (required)
   * @param headers Optional headers to include in the request
   * @return CheckDomainSuccessResponse
   * @throws ApiException if fails to make API call
   */
  public CheckDomainSuccessResponse checkCertificateDomains(@javax.annotation.Nonnull CheckDomainRequest checkDomainRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<CheckDomainSuccessResponse> localVarResponse = checkCertificateDomainsWithHttpInfo(checkDomainRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * 检查 DNS-01 CNAME 状态
   * 返回待验证域名需要配置的 CNAME 记录及当前解析状态。
   * @param checkDomainRequest  (required)
   * @return ApiResponse&lt;CheckDomainSuccessResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CheckDomainSuccessResponse> checkCertificateDomainsWithHttpInfo(@javax.annotation.Nonnull CheckDomainRequest checkDomainRequest) throws ApiException {
    return checkCertificateDomainsWithHttpInfo(checkDomainRequest, null);
  }

  /**
   * 检查 DNS-01 CNAME 状态
   * 返回待验证域名需要配置的 CNAME 记录及当前解析状态。
   * @param checkDomainRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CheckDomainSuccessResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CheckDomainSuccessResponse> checkCertificateDomainsWithHttpInfo(@javax.annotation.Nonnull CheckDomainRequest checkDomainRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = checkCertificateDomainsRequestBuilder(checkDomainRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("checkCertificateDomains", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CheckDomainSuccessResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CheckDomainSuccessResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CheckDomainSuccessResponse>() {});
        

        return new ApiResponse<CheckDomainSuccessResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder checkCertificateDomainsRequestBuilder(@javax.annotation.Nonnull CheckDomainRequest checkDomainRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'checkDomainRequest' is set
    if (checkDomainRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'checkDomainRequest' when calling checkCertificateDomains");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/cert/check-domain";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(checkDomainRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 下载证书
   * format 默认为 tar；错误始终返回非 2xx JSON envelope。
   * @param certKey 证书对外唯一标识。 (required)
   * @param format 下载格式。 (optional, default to tar)
   * @return File
   * @throws ApiException if fails to make API call
   */
  public File downloadCertificate(@javax.annotation.Nonnull String certKey, @javax.annotation.Nullable String format) throws ApiException {
    return downloadCertificate(certKey, format, null);
  }

  /**
   * 下载证书
   * format 默认为 tar；错误始终返回非 2xx JSON envelope。
   * @param certKey 证书对外唯一标识。 (required)
   * @param format 下载格式。 (optional, default to tar)
   * @param headers Optional headers to include in the request
   * @return File
   * @throws ApiException if fails to make API call
   */
  public File downloadCertificate(@javax.annotation.Nonnull String certKey, @javax.annotation.Nullable String format, Map<String, String> headers) throws ApiException {
    ApiResponse<File> localVarResponse = downloadCertificateWithHttpInfo(certKey, format, headers);
    return localVarResponse.getData();
  }

  /**
   * 下载证书
   * format 默认为 tar；错误始终返回非 2xx JSON envelope。
   * @param certKey 证书对外唯一标识。 (required)
   * @param format 下载格式。 (optional, default to tar)
   * @return ApiResponse&lt;File&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<File> downloadCertificateWithHttpInfo(@javax.annotation.Nonnull String certKey, @javax.annotation.Nullable String format) throws ApiException {
    return downloadCertificateWithHttpInfo(certKey, format, null);
  }

  /**
   * 下载证书
   * format 默认为 tar；错误始终返回非 2xx JSON envelope。
   * @param certKey 证书对外唯一标识。 (required)
   * @param format 下载格式。 (optional, default to tar)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;File&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<File> downloadCertificateWithHttpInfo(@javax.annotation.Nonnull String certKey, @javax.annotation.Nullable String format, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = downloadCertificateRequestBuilder(certKey, format, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("downloadCertificate", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<File>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        // Handle file downloading.
        File responseValue = downloadFileFromResponse(localVarResponse, localVarResponseBody);
        

        return new ApiResponse<File>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder downloadCertificateRequestBuilder(@javax.annotation.Nonnull String certKey, @javax.annotation.Nullable String format, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'certKey' is set
    if (certKey == null) {
      throw new ApiException(400, "Missing the required parameter 'certKey' when calling downloadCertificate");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/cert/{certKey}/download"
        .replace("{certKey}", ApiClient.urlEncode(certKey.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "format";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("format", format));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/x-tar, application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 查询证书详情
   * 
   * @param certKey 证书对外唯一标识。 (required)
   * @return CertificateDetailSuccessResponse
   * @throws ApiException if fails to make API call
   */
  public CertificateDetailSuccessResponse getCertificate(@javax.annotation.Nonnull String certKey) throws ApiException {
    return getCertificate(certKey, null);
  }

  /**
   * 查询证书详情
   * 
   * @param certKey 证书对外唯一标识。 (required)
   * @param headers Optional headers to include in the request
   * @return CertificateDetailSuccessResponse
   * @throws ApiException if fails to make API call
   */
  public CertificateDetailSuccessResponse getCertificate(@javax.annotation.Nonnull String certKey, Map<String, String> headers) throws ApiException {
    ApiResponse<CertificateDetailSuccessResponse> localVarResponse = getCertificateWithHttpInfo(certKey, headers);
    return localVarResponse.getData();
  }

  /**
   * 查询证书详情
   * 
   * @param certKey 证书对外唯一标识。 (required)
   * @return ApiResponse&lt;CertificateDetailSuccessResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CertificateDetailSuccessResponse> getCertificateWithHttpInfo(@javax.annotation.Nonnull String certKey) throws ApiException {
    return getCertificateWithHttpInfo(certKey, null);
  }

  /**
   * 查询证书详情
   * 
   * @param certKey 证书对外唯一标识。 (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CertificateDetailSuccessResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CertificateDetailSuccessResponse> getCertificateWithHttpInfo(@javax.annotation.Nonnull String certKey, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getCertificateRequestBuilder(certKey, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getCertificate", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CertificateDetailSuccessResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CertificateDetailSuccessResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CertificateDetailSuccessResponse>() {});
        

        return new ApiResponse<CertificateDetailSuccessResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getCertificateRequestBuilder(@javax.annotation.Nonnull String certKey, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'certKey' is set
    if (certKey == null) {
      throw new ApiException(400, "Missing the required parameter 'certKey' when calling getCertificate");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/cert/{certKey}"
        .replace("{certKey}", ApiClient.urlEncode(certKey.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 查询证书列表
   * 查询当前 AccessKey 所属用户的自动签发证书；未知 status 返回 400。
   * @param page 从 1 开始的页码。 (optional, default to 1)
   * @param size 每页数量，最大 100。 (optional, default to 20)
   * @param keyword 按证书主域名模糊搜索。 (optional)
   * @param status 按证书状态筛选。 (optional)
   * @return CertificateListSuccessResponse
   * @throws ApiException if fails to make API call
   */
  public CertificateListSuccessResponse listCertificates(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String keyword, @javax.annotation.Nullable CertificateStatus status) throws ApiException {
    return listCertificates(page, size, keyword, status, null);
  }

  /**
   * 查询证书列表
   * 查询当前 AccessKey 所属用户的自动签发证书；未知 status 返回 400。
   * @param page 从 1 开始的页码。 (optional, default to 1)
   * @param size 每页数量，最大 100。 (optional, default to 20)
   * @param keyword 按证书主域名模糊搜索。 (optional)
   * @param status 按证书状态筛选。 (optional)
   * @param headers Optional headers to include in the request
   * @return CertificateListSuccessResponse
   * @throws ApiException if fails to make API call
   */
  public CertificateListSuccessResponse listCertificates(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String keyword, @javax.annotation.Nullable CertificateStatus status, Map<String, String> headers) throws ApiException {
    ApiResponse<CertificateListSuccessResponse> localVarResponse = listCertificatesWithHttpInfo(page, size, keyword, status, headers);
    return localVarResponse.getData();
  }

  /**
   * 查询证书列表
   * 查询当前 AccessKey 所属用户的自动签发证书；未知 status 返回 400。
   * @param page 从 1 开始的页码。 (optional, default to 1)
   * @param size 每页数量，最大 100。 (optional, default to 20)
   * @param keyword 按证书主域名模糊搜索。 (optional)
   * @param status 按证书状态筛选。 (optional)
   * @return ApiResponse&lt;CertificateListSuccessResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CertificateListSuccessResponse> listCertificatesWithHttpInfo(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String keyword, @javax.annotation.Nullable CertificateStatus status) throws ApiException {
    return listCertificatesWithHttpInfo(page, size, keyword, status, null);
  }

  /**
   * 查询证书列表
   * 查询当前 AccessKey 所属用户的自动签发证书；未知 status 返回 400。
   * @param page 从 1 开始的页码。 (optional, default to 1)
   * @param size 每页数量，最大 100。 (optional, default to 20)
   * @param keyword 按证书主域名模糊搜索。 (optional)
   * @param status 按证书状态筛选。 (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CertificateListSuccessResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CertificateListSuccessResponse> listCertificatesWithHttpInfo(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String keyword, @javax.annotation.Nullable CertificateStatus status, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listCertificatesRequestBuilder(page, size, keyword, status, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listCertificates", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CertificateListSuccessResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CertificateListSuccessResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CertificateListSuccessResponse>() {});
        

        return new ApiResponse<CertificateListSuccessResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listCertificatesRequestBuilder(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String keyword, @javax.annotation.Nullable CertificateStatus status, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/cert";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParameterBaseName = "size";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("size", size));
    localVarQueryParameterBaseName = "keyword";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("keyword", keyword));
    localVarQueryParameterBaseName = "status";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("status", status));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 提交证书生命周期操作
   * 提交 apply、renew、revoke 或 delete。action 为空时默认为 apply。 apply、renew 和 revoke 返回字符串 operationId 和 requestKey；delete 同步完成。 
   * @param submitCertificateActionRequest  (required)
   * @return CertificateActionSuccessResponse
   * @throws ApiException if fails to make API call
   */
  public CertificateActionSuccessResponse submitCertificateAction(@javax.annotation.Nonnull SubmitCertificateActionRequest submitCertificateActionRequest) throws ApiException {
    return submitCertificateAction(submitCertificateActionRequest, null);
  }

  /**
   * 提交证书生命周期操作
   * 提交 apply、renew、revoke 或 delete。action 为空时默认为 apply。 apply、renew 和 revoke 返回字符串 operationId 和 requestKey；delete 同步完成。 
   * @param submitCertificateActionRequest  (required)
   * @param headers Optional headers to include in the request
   * @return CertificateActionSuccessResponse
   * @throws ApiException if fails to make API call
   */
  public CertificateActionSuccessResponse submitCertificateAction(@javax.annotation.Nonnull SubmitCertificateActionRequest submitCertificateActionRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<CertificateActionSuccessResponse> localVarResponse = submitCertificateActionWithHttpInfo(submitCertificateActionRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * 提交证书生命周期操作
   * 提交 apply、renew、revoke 或 delete。action 为空时默认为 apply。 apply、renew 和 revoke 返回字符串 operationId 和 requestKey；delete 同步完成。 
   * @param submitCertificateActionRequest  (required)
   * @return ApiResponse&lt;CertificateActionSuccessResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CertificateActionSuccessResponse> submitCertificateActionWithHttpInfo(@javax.annotation.Nonnull SubmitCertificateActionRequest submitCertificateActionRequest) throws ApiException {
    return submitCertificateActionWithHttpInfo(submitCertificateActionRequest, null);
  }

  /**
   * 提交证书生命周期操作
   * 提交 apply、renew、revoke 或 delete。action 为空时默认为 apply。 apply、renew 和 revoke 返回字符串 operationId 和 requestKey；delete 同步完成。 
   * @param submitCertificateActionRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CertificateActionSuccessResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CertificateActionSuccessResponse> submitCertificateActionWithHttpInfo(@javax.annotation.Nonnull SubmitCertificateActionRequest submitCertificateActionRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = submitCertificateActionRequestBuilder(submitCertificateActionRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("submitCertificateAction", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CertificateActionSuccessResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CertificateActionSuccessResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CertificateActionSuccessResponse>() {});
        

        return new ApiResponse<CertificateActionSuccessResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder submitCertificateActionRequestBuilder(@javax.annotation.Nonnull SubmitCertificateActionRequest submitCertificateActionRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'submitCertificateActionRequest' is set
    if (submitCertificateActionRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'submitCertificateActionRequest' when calling submitCertificateAction");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/cert/apply";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(submitCertificateActionRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
