# coding: utf-8

"""
    ANSSL OpenAPI

    ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CertificateOperationStatus(str, Enum):
    """
    异步操作执行状态。
    """

    """
    allowed enum values
    """
    PENDING = 'pending'
    RUNNING = 'running'
    WAITING_VALIDATION = 'waiting_validation'
    SUCCEEDED = 'succeeded'
    FAILED = 'failed'
    CANCELED = 'canceled'
    UNKNOWN = 'unknown'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CertificateOperationStatus from a JSON string"""
        return cls(json.loads(json_str))


