# coding: utf-8

"""
    ANSSL OpenAPI

    ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CertificateKeyAlgorithm(str, Enum):
    """
    对外统一的证书密钥算法。
    """

    """
    allowed enum values
    """
    EC256 = 'EC256'
    EC384 = 'EC384'
    RSA2048 = 'RSA2048'
    RSA4096 = 'RSA4096'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CertificateKeyAlgorithm from a JSON string"""
        return cls(json.loads(json_str))


