# coding: utf-8

"""
    ANSSL OpenAPI

    ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from anssl.models.apply_certificate_request import ApplyCertificateRequest
from anssl.models.delete_certificate_request import DeleteCertificateRequest
from anssl.models.renew_certificate_request import RenewCertificateRequest
from anssl.models.revoke_certificate_request import RevokeCertificateRequest
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

SUBMITCERTIFICATEACTIONREQUEST_ONE_OF_SCHEMAS = ["ApplyCertificateRequest", "DeleteCertificateRequest", "RenewCertificateRequest", "RevokeCertificateRequest"]

class SubmitCertificateActionRequest(BaseModel):
    """
    SubmitCertificateActionRequest
    """
    # data type: ApplyCertificateRequest
    oneof_schema_1_validator: Optional[ApplyCertificateRequest] = None
    # data type: RenewCertificateRequest
    oneof_schema_2_validator: Optional[RenewCertificateRequest] = None
    # data type: RevokeCertificateRequest
    oneof_schema_3_validator: Optional[RevokeCertificateRequest] = None
    # data type: DeleteCertificateRequest
    oneof_schema_4_validator: Optional[DeleteCertificateRequest] = None
    actual_instance: Optional[Union[ApplyCertificateRequest, DeleteCertificateRequest, RenewCertificateRequest, RevokeCertificateRequest]] = None
    one_of_schemas: Set[str] = { "ApplyCertificateRequest", "DeleteCertificateRequest", "RenewCertificateRequest", "RevokeCertificateRequest" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = SubmitCertificateActionRequest.model_construct()
        error_messages = []
        match = 0
        # validate data type: ApplyCertificateRequest
        if not isinstance(v, ApplyCertificateRequest):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ApplyCertificateRequest`")
        else:
            match += 1
        # validate data type: RenewCertificateRequest
        if not isinstance(v, RenewCertificateRequest):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RenewCertificateRequest`")
        else:
            match += 1
        # validate data type: RevokeCertificateRequest
        if not isinstance(v, RevokeCertificateRequest):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RevokeCertificateRequest`")
        else:
            match += 1
        # validate data type: DeleteCertificateRequest
        if not isinstance(v, DeleteCertificateRequest):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DeleteCertificateRequest`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in SubmitCertificateActionRequest with oneOf schemas: ApplyCertificateRequest, DeleteCertificateRequest, RenewCertificateRequest, RevokeCertificateRequest. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in SubmitCertificateActionRequest with oneOf schemas: ApplyCertificateRequest, DeleteCertificateRequest, RenewCertificateRequest, RevokeCertificateRequest. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ApplyCertificateRequest
        try:
            instance.actual_instance = ApplyCertificateRequest.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RenewCertificateRequest
        try:
            instance.actual_instance = RenewCertificateRequest.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RevokeCertificateRequest
        try:
            instance.actual_instance = RevokeCertificateRequest.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DeleteCertificateRequest
        try:
            instance.actual_instance = DeleteCertificateRequest.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into SubmitCertificateActionRequest with oneOf schemas: ApplyCertificateRequest, DeleteCertificateRequest, RenewCertificateRequest, RevokeCertificateRequest. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into SubmitCertificateActionRequest with oneOf schemas: ApplyCertificateRequest, DeleteCertificateRequest, RenewCertificateRequest, RevokeCertificateRequest. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ApplyCertificateRequest, DeleteCertificateRequest, RenewCertificateRequest, RevokeCertificateRequest]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


