# coding: utf-8

"""
    ANSSL OpenAPI

    ANSSL 证书生命周期公开 REST API。所有请求使用 Bearer AccessKey。 成功响应使用 code=0 envelope；错误响应的 HTTP 状态与数字 code 保持一致。 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class VerificationType(str, Enum):
    """
    ACME 验证方式。
    """

    """
    allowed enum values
    """
    DNS = 'dns'
    HTTP = 'http'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of VerificationType from a JSON string"""
        return cls(json.loads(json_str))


